// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
  id, user_id, broker_name, account_type, currency, balance, leverage, 
  max_risk_per_trade, max_daily_risk
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, user_id, broker_name, account_type, currency, balance, leverage, max_risk_per_trade, max_daily_risk, created_at, updated_at
`

type CreateAccountParams struct {
	ID              uuid.UUID     `json:"id"`
	UserID          uuid.UUID     `json:"user_id"`
	BrokerName      string        `json:"broker_name"`
	AccountType     string        `json:"account_type"`
	Currency        pgtype.Text   `json:"currency"`
	Balance         float64       `json:"balance"`
	Leverage        pgtype.Text   `json:"leverage"`
	MaxRiskPerTrade pgtype.Float8 `json:"max_risk_per_trade"`
	MaxDailyRisk    pgtype.Float8 `json:"max_daily_risk"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.UserID,
		arg.BrokerName,
		arg.AccountType,
		arg.Currency,
		arg.Balance,
		arg.Leverage,
		arg.MaxRiskPerTrade,
		arg.MaxDailyRisk,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BrokerName,
		&i.AccountType,
		&i.Currency,
		&i.Balance,
		&i.Leverage,
		&i.MaxRiskPerTrade,
		&i.MaxDailyRisk,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, user_id, broker_name, account_type, currency, balance, leverage, max_risk_per_trade, max_daily_risk, created_at, updated_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BrokerName,
		&i.AccountType,
		&i.Currency,
		&i.Balance,
		&i.Leverage,
		&i.MaxRiskPerTrade,
		&i.MaxDailyRisk,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccountsByUser = `-- name: ListAccountsByUser :many
SELECT id, user_id, broker_name, account_type, currency, balance, leverage, max_risk_per_trade, max_daily_risk, created_at, updated_at FROM accounts WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAccountsByUser(ctx context.Context, userID uuid.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BrokerName,
			&i.AccountType,
			&i.Currency,
			&i.Balance,
			&i.Leverage,
			&i.MaxRiskPerTrade,
			&i.MaxDailyRisk,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
