// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    id,
    user_id,
    type,
    broker_name,
    currency,
    balance,
    leverage,
    max_risk_per_trade_pct,
    max_daily_risk_pct,
    timezone,
    preferred_session,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW()
)
RETURNING id, user_id, type, broker_name, currency, balance, leverage, max_risk_per_trade_pct, max_daily_risk_pct, timezone, preferred_session, updated_at
`

type CreateAccountParams struct {
	ID                 uuid.UUID       `json:"id"`
	UserID             uuid.UUID       `json:"user_id"`
	Type               AccountType     `json:"type"`
	BrokerName         string          `json:"broker_name"`
	Currency           string          `json:"currency"`
	Balance            decimal.Decimal `json:"balance"`
	Leverage           int32           `json:"leverage"`
	MaxRiskPerTradePct decimal.Decimal `json:"max_risk_per_trade_pct"`
	MaxDailyRiskPct    decimal.Decimal `json:"max_daily_risk_pct"`
	Timezone           string          `json:"timezone"`
	PreferredSession   SessionType     `json:"preferred_session"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.BrokerName,
		arg.Currency,
		arg.Balance,
		arg.Leverage,
		arg.MaxRiskPerTradePct,
		arg.MaxDailyRiskPct,
		arg.Timezone,
		arg.PreferredSession,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.BrokerName,
		&i.Currency,
		&i.Balance,
		&i.Leverage,
		&i.MaxRiskPerTradePct,
		&i.MaxDailyRiskPct,
		&i.Timezone,
		&i.PreferredSession,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, user_id, type, broker_name, currency, balance, leverage, max_risk_per_trade_pct, max_daily_risk_pct, timezone, preferred_session, updated_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.BrokerName,
		&i.Currency,
		&i.Balance,
		&i.Leverage,
		&i.MaxRiskPerTradePct,
		&i.MaxDailyRiskPct,
		&i.Timezone,
		&i.PreferredSession,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountsByUserID = `-- name: GetAccountsByUserID :many
SELECT id, user_id, type, broker_name, currency, balance, leverage, max_risk_per_trade_pct, max_daily_risk_pct, timezone, preferred_session, updated_at FROM accounts WHERE user_id = $1
`

func (q *Queries) GetAccountsByUserID(ctx context.Context, userID uuid.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, getAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.BrokerName,
			&i.Currency,
			&i.Balance,
			&i.Leverage,
			&i.MaxRiskPerTradePct,
			&i.MaxDailyRiskPct,
			&i.Timezone,
			&i.PreferredSession,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
