// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: backtest.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countBacktestTradesByResult = `-- name: CountBacktestTradesByResult :one
SELECT COUNT(*) FROM backtest_trades 
WHERE backtest_run_id = $1 AND trade_result = $2
`

type CountBacktestTradesByResultParams struct {
	BacktestRunID pgtype.UUID `json:"backtest_run_id"`
	TradeResult   string      `json:"trade_result"`
}

func (q *Queries) CountBacktestTradesByResult(ctx context.Context, arg CountBacktestTradesByResultParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBacktestTradesByResult, arg.BacktestRunID, arg.TradeResult)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWalkforwardValidationsByStatus = `-- name: CountWalkforwardValidationsByStatus :one
SELECT COUNT(*) FROM walkforward_validation 
WHERE strategy_name = $1 AND status = $2
`

type CountWalkforwardValidationsByStatusParams struct {
	StrategyName string `json:"strategy_name"`
	Status       string `json:"status"`
}

func (q *Queries) CountWalkforwardValidationsByStatus(ctx context.Context, arg CountWalkforwardValidationsByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWalkforwardValidationsByStatus, arg.StrategyName, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBacktestRunByID = `-- name: GetBacktestRunByID :one
SELECT id, strategy_name, symbol, timeframe, execution_timeframe, start_date, end_date, total_patterns, traded_patterns, filtered_patterns, total_trades, winning_trades, losing_trades, breakeven_trades, win_rate, avg_win, avg_loss, avg_rr, expectancy, profit_factor, max_drawdown, sharpe_ratio, total_pnl, confidence_threshold, min_rr, created_at FROM backtest_runs WHERE id = $1
`

func (q *Queries) GetBacktestRunByID(ctx context.Context, id uuid.UUID) (BacktestRun, error) {
	row := q.db.QueryRow(ctx, getBacktestRunByID, id)
	var i BacktestRun
	err := row.Scan(
		&i.ID,
		&i.StrategyName,
		&i.Symbol,
		&i.Timeframe,
		&i.ExecutionTimeframe,
		&i.StartDate,
		&i.EndDate,
		&i.TotalPatterns,
		&i.TradedPatterns,
		&i.FilteredPatterns,
		&i.TotalTrades,
		&i.WinningTrades,
		&i.LosingTrades,
		&i.BreakevenTrades,
		&i.WinRate,
		&i.AvgWin,
		&i.AvgLoss,
		&i.AvgRr,
		&i.Expectancy,
		&i.ProfitFactor,
		&i.MaxDrawdown,
		&i.SharpeRatio,
		&i.TotalPnl,
		&i.ConfidenceThreshold,
		&i.MinRr,
		&i.CreatedAt,
	)
	return i, err
}

const getBacktestRunsByStrategy = `-- name: GetBacktestRunsByStrategy :many
SELECT id, strategy_name, symbol, timeframe, execution_timeframe, start_date, end_date, total_patterns, traded_patterns, filtered_patterns, total_trades, winning_trades, losing_trades, breakeven_trades, win_rate, avg_win, avg_loss, avg_rr, expectancy, profit_factor, max_drawdown, sharpe_ratio, total_pnl, confidence_threshold, min_rr, created_at FROM backtest_runs 
WHERE strategy_name = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetBacktestRunsByStrategyParams struct {
	StrategyName string `json:"strategy_name"`
	Limit        int32  `json:"limit"`
}

func (q *Queries) GetBacktestRunsByStrategy(ctx context.Context, arg GetBacktestRunsByStrategyParams) ([]BacktestRun, error) {
	rows, err := q.db.Query(ctx, getBacktestRunsByStrategy, arg.StrategyName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BacktestRun
	for rows.Next() {
		var i BacktestRun
		if err := rows.Scan(
			&i.ID,
			&i.StrategyName,
			&i.Symbol,
			&i.Timeframe,
			&i.ExecutionTimeframe,
			&i.StartDate,
			&i.EndDate,
			&i.TotalPatterns,
			&i.TradedPatterns,
			&i.FilteredPatterns,
			&i.TotalTrades,
			&i.WinningTrades,
			&i.LosingTrades,
			&i.BreakevenTrades,
			&i.WinRate,
			&i.AvgWin,
			&i.AvgLoss,
			&i.AvgRr,
			&i.Expectancy,
			&i.ProfitFactor,
			&i.MaxDrawdown,
			&i.SharpeRatio,
			&i.TotalPnl,
			&i.ConfidenceThreshold,
			&i.MinRr,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBacktestTradesByResult = `-- name: GetBacktestTradesByResult :many
SELECT id, backtest_run_id, pattern_detection_id, signal_id, symbol, timeframe, execution_timeframe, entry_time, exit_time, entry_price, exit_price, pnl, pnl_r, rr_ratio, trade_result, reason, created_at FROM backtest_trades 
WHERE backtest_run_id = $1 AND trade_result = $2
ORDER BY entry_time ASC
`

type GetBacktestTradesByResultParams struct {
	BacktestRunID pgtype.UUID `json:"backtest_run_id"`
	TradeResult   string      `json:"trade_result"`
}

func (q *Queries) GetBacktestTradesByResult(ctx context.Context, arg GetBacktestTradesByResultParams) ([]BacktestTrade, error) {
	rows, err := q.db.Query(ctx, getBacktestTradesByResult, arg.BacktestRunID, arg.TradeResult)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BacktestTrade
	for rows.Next() {
		var i BacktestTrade
		if err := rows.Scan(
			&i.ID,
			&i.BacktestRunID,
			&i.PatternDetectionID,
			&i.SignalID,
			&i.Symbol,
			&i.Timeframe,
			&i.ExecutionTimeframe,
			&i.EntryTime,
			&i.ExitTime,
			&i.EntryPrice,
			&i.ExitPrice,
			&i.Pnl,
			&i.PnlR,
			&i.RrRatio,
			&i.TradeResult,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBacktestTradesByRun = `-- name: GetBacktestTradesByRun :many
SELECT id, backtest_run_id, pattern_detection_id, signal_id, symbol, timeframe, execution_timeframe, entry_time, exit_time, entry_price, exit_price, pnl, pnl_r, rr_ratio, trade_result, reason, created_at FROM backtest_trades 
WHERE backtest_run_id = $1
ORDER BY entry_time ASC
`

func (q *Queries) GetBacktestTradesByRun(ctx context.Context, backtestRunID pgtype.UUID) ([]BacktestTrade, error) {
	rows, err := q.db.Query(ctx, getBacktestTradesByRun, backtestRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BacktestTrade
	for rows.Next() {
		var i BacktestTrade
		if err := rows.Scan(
			&i.ID,
			&i.BacktestRunID,
			&i.PatternDetectionID,
			&i.SignalID,
			&i.Symbol,
			&i.Timeframe,
			&i.ExecutionTimeframe,
			&i.EntryTime,
			&i.ExitTime,
			&i.EntryPrice,
			&i.ExitPrice,
			&i.Pnl,
			&i.PnlR,
			&i.RrRatio,
			&i.TradeResult,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestBacktestRun = `-- name: GetLatestBacktestRun :one
SELECT id, strategy_name, symbol, timeframe, execution_timeframe, start_date, end_date, total_patterns, traded_patterns, filtered_patterns, total_trades, winning_trades, losing_trades, breakeven_trades, win_rate, avg_win, avg_loss, avg_rr, expectancy, profit_factor, max_drawdown, sharpe_ratio, total_pnl, confidence_threshold, min_rr, created_at FROM backtest_runs 
WHERE strategy_name = $1 AND symbol = $2 AND timeframe = $3
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestBacktestRunParams struct {
	StrategyName string        `json:"strategy_name"`
	Symbol       string        `json:"symbol"`
	Timeframe    RuleTimeframe `json:"timeframe"`
}

func (q *Queries) GetLatestBacktestRun(ctx context.Context, arg GetLatestBacktestRunParams) (BacktestRun, error) {
	row := q.db.QueryRow(ctx, getLatestBacktestRun, arg.StrategyName, arg.Symbol, arg.Timeframe)
	var i BacktestRun
	err := row.Scan(
		&i.ID,
		&i.StrategyName,
		&i.Symbol,
		&i.Timeframe,
		&i.ExecutionTimeframe,
		&i.StartDate,
		&i.EndDate,
		&i.TotalPatterns,
		&i.TradedPatterns,
		&i.FilteredPatterns,
		&i.TotalTrades,
		&i.WinningTrades,
		&i.LosingTrades,
		&i.BreakevenTrades,
		&i.WinRate,
		&i.AvgWin,
		&i.AvgLoss,
		&i.AvgRr,
		&i.Expectancy,
		&i.ProfitFactor,
		&i.MaxDrawdown,
		&i.SharpeRatio,
		&i.TotalPnl,
		&i.ConfidenceThreshold,
		&i.MinRr,
		&i.CreatedAt,
	)
	return i, err
}

const getWalkforwardValidationsByStatus = `-- name: GetWalkforwardValidationsByStatus :many
SELECT id, strategy_name, symbol, timeframe, execution_timeframe, in_sample_start, in_sample_end, in_sample_expectancy, in_sample_trades, out_sample_start, out_sample_end, out_sample_expectancy, out_sample_trades, walkforward_efficiency, status, created_at FROM walkforward_validation 
WHERE strategy_name = $1 AND status = $2
ORDER BY created_at DESC
`

type GetWalkforwardValidationsByStatusParams struct {
	StrategyName string `json:"strategy_name"`
	Status       string `json:"status"`
}

func (q *Queries) GetWalkforwardValidationsByStatus(ctx context.Context, arg GetWalkforwardValidationsByStatusParams) ([]WalkforwardValidation, error) {
	rows, err := q.db.Query(ctx, getWalkforwardValidationsByStatus, arg.StrategyName, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WalkforwardValidation
	for rows.Next() {
		var i WalkforwardValidation
		if err := rows.Scan(
			&i.ID,
			&i.StrategyName,
			&i.Symbol,
			&i.Timeframe,
			&i.ExecutionTimeframe,
			&i.InSampleStart,
			&i.InSampleEnd,
			&i.InSampleExpectancy,
			&i.InSampleTrades,
			&i.OutSampleStart,
			&i.OutSampleEnd,
			&i.OutSampleExpectancy,
			&i.OutSampleTrades,
			&i.WalkforwardEfficiency,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWalkforwardValidationsByStrategy = `-- name: GetWalkforwardValidationsByStrategy :many
SELECT id, strategy_name, symbol, timeframe, execution_timeframe, in_sample_start, in_sample_end, in_sample_expectancy, in_sample_trades, out_sample_start, out_sample_end, out_sample_expectancy, out_sample_trades, walkforward_efficiency, status, created_at FROM walkforward_validation 
WHERE strategy_name = $1
ORDER BY in_sample_start ASC
`

func (q *Queries) GetWalkforwardValidationsByStrategy(ctx context.Context, strategyName string) ([]WalkforwardValidation, error) {
	rows, err := q.db.Query(ctx, getWalkforwardValidationsByStrategy, strategyName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WalkforwardValidation
	for rows.Next() {
		var i WalkforwardValidation
		if err := rows.Scan(
			&i.ID,
			&i.StrategyName,
			&i.Symbol,
			&i.Timeframe,
			&i.ExecutionTimeframe,
			&i.InSampleStart,
			&i.InSampleEnd,
			&i.InSampleExpectancy,
			&i.InSampleTrades,
			&i.OutSampleStart,
			&i.OutSampleEnd,
			&i.OutSampleExpectancy,
			&i.OutSampleTrades,
			&i.WalkforwardEfficiency,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBacktestRun = `-- name: InsertBacktestRun :one
INSERT INTO backtest_runs (
    strategy_name, symbol, timeframe, execution_timeframe,
    start_date, end_date,
    total_patterns, traded_patterns, filtered_patterns,
    total_trades, winning_trades, losing_trades, breakeven_trades,
    win_rate, avg_win, avg_loss, avg_rr, expectancy,
    profit_factor, max_drawdown, sharpe_ratio, total_pnl,
    confidence_threshold, min_rr
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13,
    $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24
)
RETURNING id, strategy_name, symbol, timeframe, execution_timeframe, start_date, end_date, total_patterns, traded_patterns, filtered_patterns, total_trades, winning_trades, losing_trades, breakeven_trades, win_rate, avg_win, avg_loss, avg_rr, expectancy, profit_factor, max_drawdown, sharpe_ratio, total_pnl, confidence_threshold, min_rr, created_at
`

type InsertBacktestRunParams struct {
	StrategyName        string          `json:"strategy_name"`
	Symbol              string          `json:"symbol"`
	Timeframe           RuleTimeframe   `json:"timeframe"`
	ExecutionTimeframe  RuleTimeframe   `json:"execution_timeframe"`
	StartDate           pgtype.Date     `json:"start_date"`
	EndDate             pgtype.Date     `json:"end_date"`
	TotalPatterns       int32           `json:"total_patterns"`
	TradedPatterns      int32           `json:"traded_patterns"`
	FilteredPatterns    int32           `json:"filtered_patterns"`
	TotalTrades         int32           `json:"total_trades"`
	WinningTrades       int32           `json:"winning_trades"`
	LosingTrades        int32           `json:"losing_trades"`
	BreakevenTrades     int32           `json:"breakeven_trades"`
	WinRate             decimal.Decimal `json:"win_rate"`
	AvgWin              decimal.Decimal `json:"avg_win"`
	AvgLoss             decimal.Decimal `json:"avg_loss"`
	AvgRr               decimal.Decimal `json:"avg_rr"`
	Expectancy          decimal.Decimal `json:"expectancy"`
	ProfitFactor        decimal.Decimal `json:"profit_factor"`
	MaxDrawdown         decimal.Decimal `json:"max_drawdown"`
	SharpeRatio         decimal.Decimal `json:"sharpe_ratio"`
	TotalPnl            decimal.Decimal `json:"total_pnl"`
	ConfidenceThreshold decimal.Decimal `json:"confidence_threshold"`
	MinRr               decimal.Decimal `json:"min_rr"`
}

func (q *Queries) InsertBacktestRun(ctx context.Context, arg InsertBacktestRunParams) (BacktestRun, error) {
	row := q.db.QueryRow(ctx, insertBacktestRun,
		arg.StrategyName,
		arg.Symbol,
		arg.Timeframe,
		arg.ExecutionTimeframe,
		arg.StartDate,
		arg.EndDate,
		arg.TotalPatterns,
		arg.TradedPatterns,
		arg.FilteredPatterns,
		arg.TotalTrades,
		arg.WinningTrades,
		arg.LosingTrades,
		arg.BreakevenTrades,
		arg.WinRate,
		arg.AvgWin,
		arg.AvgLoss,
		arg.AvgRr,
		arg.Expectancy,
		arg.ProfitFactor,
		arg.MaxDrawdown,
		arg.SharpeRatio,
		arg.TotalPnl,
		arg.ConfidenceThreshold,
		arg.MinRr,
	)
	var i BacktestRun
	err := row.Scan(
		&i.ID,
		&i.StrategyName,
		&i.Symbol,
		&i.Timeframe,
		&i.ExecutionTimeframe,
		&i.StartDate,
		&i.EndDate,
		&i.TotalPatterns,
		&i.TradedPatterns,
		&i.FilteredPatterns,
		&i.TotalTrades,
		&i.WinningTrades,
		&i.LosingTrades,
		&i.BreakevenTrades,
		&i.WinRate,
		&i.AvgWin,
		&i.AvgLoss,
		&i.AvgRr,
		&i.Expectancy,
		&i.ProfitFactor,
		&i.MaxDrawdown,
		&i.SharpeRatio,
		&i.TotalPnl,
		&i.ConfidenceThreshold,
		&i.MinRr,
		&i.CreatedAt,
	)
	return i, err
}

const insertBacktestTrade = `-- name: InsertBacktestTrade :one
INSERT INTO backtest_trades (
    backtest_run_id, pattern_detection_id, signal_id,
    symbol, timeframe, execution_timeframe,
    entry_time, exit_time, entry_price, exit_price,
    pnl, pnl_r, rr_ratio, trade_result, reason
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, backtest_run_id, pattern_detection_id, signal_id, symbol, timeframe, execution_timeframe, entry_time, exit_time, entry_price, exit_price, pnl, pnl_r, rr_ratio, trade_result, reason, created_at
`

type InsertBacktestTradeParams struct {
	BacktestRunID      pgtype.UUID        `json:"backtest_run_id"`
	PatternDetectionID pgtype.UUID        `json:"pattern_detection_id"`
	SignalID           pgtype.UUID        `json:"signal_id"`
	Symbol             string             `json:"symbol"`
	Timeframe          RuleTimeframe      `json:"timeframe"`
	ExecutionTimeframe RuleTimeframe      `json:"execution_timeframe"`
	EntryTime          pgtype.Timestamptz `json:"entry_time"`
	ExitTime           pgtype.Timestamptz `json:"exit_time"`
	EntryPrice         decimal.Decimal    `json:"entry_price"`
	ExitPrice          decimal.Decimal    `json:"exit_price"`
	Pnl                decimal.Decimal    `json:"pnl"`
	PnlR               decimal.Decimal    `json:"pnl_r"`
	RrRatio            decimal.Decimal    `json:"rr_ratio"`
	TradeResult        string             `json:"trade_result"`
	Reason             pgtype.Text        `json:"reason"`
}

func (q *Queries) InsertBacktestTrade(ctx context.Context, arg InsertBacktestTradeParams) (BacktestTrade, error) {
	row := q.db.QueryRow(ctx, insertBacktestTrade,
		arg.BacktestRunID,
		arg.PatternDetectionID,
		arg.SignalID,
		arg.Symbol,
		arg.Timeframe,
		arg.ExecutionTimeframe,
		arg.EntryTime,
		arg.ExitTime,
		arg.EntryPrice,
		arg.ExitPrice,
		arg.Pnl,
		arg.PnlR,
		arg.RrRatio,
		arg.TradeResult,
		arg.Reason,
	)
	var i BacktestTrade
	err := row.Scan(
		&i.ID,
		&i.BacktestRunID,
		&i.PatternDetectionID,
		&i.SignalID,
		&i.Symbol,
		&i.Timeframe,
		&i.ExecutionTimeframe,
		&i.EntryTime,
		&i.ExitTime,
		&i.EntryPrice,
		&i.ExitPrice,
		&i.Pnl,
		&i.PnlR,
		&i.RrRatio,
		&i.TradeResult,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const insertWalkforwardValidation = `-- name: InsertWalkforwardValidation :one
INSERT INTO walkforward_validation (
    strategy_name, symbol, timeframe, execution_timeframe,
    in_sample_start, in_sample_end, in_sample_expectancy, in_sample_trades,
    out_sample_start, out_sample_end, out_sample_expectancy, out_sample_trades,
    walkforward_efficiency, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, strategy_name, symbol, timeframe, execution_timeframe, in_sample_start, in_sample_end, in_sample_expectancy, in_sample_trades, out_sample_start, out_sample_end, out_sample_expectancy, out_sample_trades, walkforward_efficiency, status, created_at
`

type InsertWalkforwardValidationParams struct {
	StrategyName          string          `json:"strategy_name"`
	Symbol                string          `json:"symbol"`
	Timeframe             RuleTimeframe   `json:"timeframe"`
	ExecutionTimeframe    RuleTimeframe   `json:"execution_timeframe"`
	InSampleStart         pgtype.Date     `json:"in_sample_start"`
	InSampleEnd           pgtype.Date     `json:"in_sample_end"`
	InSampleExpectancy    decimal.Decimal `json:"in_sample_expectancy"`
	InSampleTrades        int32           `json:"in_sample_trades"`
	OutSampleStart        pgtype.Date     `json:"out_sample_start"`
	OutSampleEnd          pgtype.Date     `json:"out_sample_end"`
	OutSampleExpectancy   decimal.Decimal `json:"out_sample_expectancy"`
	OutSampleTrades       int32           `json:"out_sample_trades"`
	WalkforwardEfficiency decimal.Decimal `json:"walkforward_efficiency"`
	Status                string          `json:"status"`
}

func (q *Queries) InsertWalkforwardValidation(ctx context.Context, arg InsertWalkforwardValidationParams) (WalkforwardValidation, error) {
	row := q.db.QueryRow(ctx, insertWalkforwardValidation,
		arg.StrategyName,
		arg.Symbol,
		arg.Timeframe,
		arg.ExecutionTimeframe,
		arg.InSampleStart,
		arg.InSampleEnd,
		arg.InSampleExpectancy,
		arg.InSampleTrades,
		arg.OutSampleStart,
		arg.OutSampleEnd,
		arg.OutSampleExpectancy,
		arg.OutSampleTrades,
		arg.WalkforwardEfficiency,
		arg.Status,
	)
	var i WalkforwardValidation
	err := row.Scan(
		&i.ID,
		&i.StrategyName,
		&i.Symbol,
		&i.Timeframe,
		&i.ExecutionTimeframe,
		&i.InSampleStart,
		&i.InSampleEnd,
		&i.InSampleExpectancy,
		&i.InSampleTrades,
		&i.OutSampleStart,
		&i.OutSampleEnd,
		&i.OutSampleExpectancy,
		&i.OutSampleTrades,
		&i.WalkforwardEfficiency,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
