// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: candles_multi_tf.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countCandlesD1 = `-- name: CountCandlesD1 :one
SELECT COUNT(*) FROM candles_d1
`

func (q *Queries) CountCandlesD1(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCandlesD1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCandlesH1 = `-- name: CountCandlesH1 :one
SELECT COUNT(*) FROM candles_h1
`

func (q *Queries) CountCandlesH1(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCandlesH1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCandlesH4 = `-- name: CountCandlesH4 :one
SELECT COUNT(*) FROM candles_h4
`

func (q *Queries) CountCandlesH4(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCandlesH4)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCandleD1ByTimestamp = `-- name: GetCandleD1ByTimestamp :one
SELECT id, timestamp_utc, open, high, low, close, volume, created_at FROM candles_d1 
WHERE timestamp_utc = $1
`

func (q *Queries) GetCandleD1ByTimestamp(ctx context.Context, timestampUtc pgtype.Timestamptz) (CandlesD1, error) {
	row := q.db.QueryRow(ctx, getCandleD1ByTimestamp, timestampUtc)
	var i CandlesD1
	err := row.Scan(
		&i.ID,
		&i.TimestampUtc,
		&i.Open,
		&i.High,
		&i.Low,
		&i.Close,
		&i.Volume,
		&i.CreatedAt,
	)
	return i, err
}

const getCandleH1ByTimestamp = `-- name: GetCandleH1ByTimestamp :one
SELECT id, timestamp_utc, open, high, low, close, volume, created_at FROM candles_h1 
WHERE timestamp_utc = $1
`

func (q *Queries) GetCandleH1ByTimestamp(ctx context.Context, timestampUtc pgtype.Timestamptz) (CandlesH1, error) {
	row := q.db.QueryRow(ctx, getCandleH1ByTimestamp, timestampUtc)
	var i CandlesH1
	err := row.Scan(
		&i.ID,
		&i.TimestampUtc,
		&i.Open,
		&i.High,
		&i.Low,
		&i.Close,
		&i.Volume,
		&i.CreatedAt,
	)
	return i, err
}

const getCandleH4ByTimestamp = `-- name: GetCandleH4ByTimestamp :one
SELECT id, timestamp_utc, open, high, low, close, volume, created_at FROM candles_h4 
WHERE timestamp_utc = $1
`

func (q *Queries) GetCandleH4ByTimestamp(ctx context.Context, timestampUtc pgtype.Timestamptz) (CandlesH4, error) {
	row := q.db.QueryRow(ctx, getCandleH4ByTimestamp, timestampUtc)
	var i CandlesH4
	err := row.Scan(
		&i.ID,
		&i.TimestampUtc,
		&i.Open,
		&i.High,
		&i.Low,
		&i.Close,
		&i.Volume,
		&i.CreatedAt,
	)
	return i, err
}

const getCandlesD1ByRange = `-- name: GetCandlesD1ByRange :many
SELECT id, timestamp_utc, open, high, low, close, volume, created_at FROM candles_d1 
WHERE timestamp_utc >= $1 AND timestamp_utc <= $2
ORDER BY timestamp_utc ASC
`

type GetCandlesD1ByRangeParams struct {
	TimestampUtc   pgtype.Timestamptz `json:"timestamp_utc"`
	TimestampUtc_2 pgtype.Timestamptz `json:"timestamp_utc_2"`
}

func (q *Queries) GetCandlesD1ByRange(ctx context.Context, arg GetCandlesD1ByRangeParams) ([]CandlesD1, error) {
	rows, err := q.db.Query(ctx, getCandlesD1ByRange, arg.TimestampUtc, arg.TimestampUtc_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CandlesD1
	for rows.Next() {
		var i CandlesD1
		if err := rows.Scan(
			&i.ID,
			&i.TimestampUtc,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCandlesD1Last = `-- name: GetCandlesD1Last :many
SELECT id, timestamp_utc, open, high, low, close, volume, created_at FROM candles_d1 
ORDER BY timestamp_utc DESC
LIMIT $1
`

func (q *Queries) GetCandlesD1Last(ctx context.Context, limit int32) ([]CandlesD1, error) {
	rows, err := q.db.Query(ctx, getCandlesD1Last, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CandlesD1
	for rows.Next() {
		var i CandlesD1
		if err := rows.Scan(
			&i.ID,
			&i.TimestampUtc,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCandlesH1ByRange = `-- name: GetCandlesH1ByRange :many
SELECT id, timestamp_utc, open, high, low, close, volume, created_at FROM candles_h1 
WHERE timestamp_utc >= $1 AND timestamp_utc <= $2
ORDER BY timestamp_utc ASC
`

type GetCandlesH1ByRangeParams struct {
	TimestampUtc   pgtype.Timestamptz `json:"timestamp_utc"`
	TimestampUtc_2 pgtype.Timestamptz `json:"timestamp_utc_2"`
}

func (q *Queries) GetCandlesH1ByRange(ctx context.Context, arg GetCandlesH1ByRangeParams) ([]CandlesH1, error) {
	rows, err := q.db.Query(ctx, getCandlesH1ByRange, arg.TimestampUtc, arg.TimestampUtc_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CandlesH1
	for rows.Next() {
		var i CandlesH1
		if err := rows.Scan(
			&i.ID,
			&i.TimestampUtc,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCandlesH1Last = `-- name: GetCandlesH1Last :many
SELECT id, timestamp_utc, open, high, low, close, volume, created_at FROM candles_h1 
ORDER BY timestamp_utc DESC
LIMIT $1
`

func (q *Queries) GetCandlesH1Last(ctx context.Context, limit int32) ([]CandlesH1, error) {
	rows, err := q.db.Query(ctx, getCandlesH1Last, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CandlesH1
	for rows.Next() {
		var i CandlesH1
		if err := rows.Scan(
			&i.ID,
			&i.TimestampUtc,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCandlesH4ByRange = `-- name: GetCandlesH4ByRange :many
SELECT id, timestamp_utc, open, high, low, close, volume, created_at FROM candles_h4 
WHERE timestamp_utc >= $1 AND timestamp_utc <= $2
ORDER BY timestamp_utc ASC
`

type GetCandlesH4ByRangeParams struct {
	TimestampUtc   pgtype.Timestamptz `json:"timestamp_utc"`
	TimestampUtc_2 pgtype.Timestamptz `json:"timestamp_utc_2"`
}

func (q *Queries) GetCandlesH4ByRange(ctx context.Context, arg GetCandlesH4ByRangeParams) ([]CandlesH4, error) {
	rows, err := q.db.Query(ctx, getCandlesH4ByRange, arg.TimestampUtc, arg.TimestampUtc_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CandlesH4
	for rows.Next() {
		var i CandlesH4
		if err := rows.Scan(
			&i.ID,
			&i.TimestampUtc,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCandlesH4Last = `-- name: GetCandlesH4Last :many
SELECT id, timestamp_utc, open, high, low, close, volume, created_at FROM candles_h4 
ORDER BY timestamp_utc DESC
LIMIT $1
`

func (q *Queries) GetCandlesH4Last(ctx context.Context, limit int32) ([]CandlesH4, error) {
	rows, err := q.db.Query(ctx, getCandlesH4Last, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CandlesH4
	for rows.Next() {
		var i CandlesH4
		if err := rows.Scan(
			&i.ID,
			&i.TimestampUtc,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCandlesWeeklyByRange = `-- name: GetCandlesWeeklyByRange :many
SELECT id, timestamp_utc, open, high, low, close, volume, created_at FROM candles_weekly 
WHERE timestamp_utc >= $1 AND timestamp_utc <= $2
ORDER BY timestamp_utc ASC
`

type GetCandlesWeeklyByRangeParams struct {
	TimestampUtc   pgtype.Timestamptz `json:"timestamp_utc"`
	TimestampUtc_2 pgtype.Timestamptz `json:"timestamp_utc_2"`
}

func (q *Queries) GetCandlesWeeklyByRange(ctx context.Context, arg GetCandlesWeeklyByRangeParams) ([]CandlesWeekly, error) {
	rows, err := q.db.Query(ctx, getCandlesWeeklyByRange, arg.TimestampUtc, arg.TimestampUtc_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CandlesWeekly
	for rows.Next() {
		var i CandlesWeekly
		if err := rows.Scan(
			&i.ID,
			&i.TimestampUtc,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCandleD1 = `-- name: InsertCandleD1 :one
INSERT INTO candles_d1 (timestamp_utc, open, high, low, close, volume)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (timestamp_utc) DO UPDATE SET
    open = EXCLUDED.open,
    high = EXCLUDED.high,
    low = EXCLUDED.low,
    close = EXCLUDED.close,
    volume = EXCLUDED.volume
RETURNING id, timestamp_utc, open, high, low, close, volume, created_at
`

type InsertCandleD1Params struct {
	TimestampUtc pgtype.Timestamptz `json:"timestamp_utc"`
	Open         decimal.Decimal    `json:"open"`
	High         decimal.Decimal    `json:"high"`
	Low          decimal.Decimal    `json:"low"`
	Close        decimal.Decimal    `json:"close"`
	Volume       pgtype.Int8        `json:"volume"`
}

func (q *Queries) InsertCandleD1(ctx context.Context, arg InsertCandleD1Params) (CandlesD1, error) {
	row := q.db.QueryRow(ctx, insertCandleD1,
		arg.TimestampUtc,
		arg.Open,
		arg.High,
		arg.Low,
		arg.Close,
		arg.Volume,
	)
	var i CandlesD1
	err := row.Scan(
		&i.ID,
		&i.TimestampUtc,
		&i.Open,
		&i.High,
		&i.Low,
		&i.Close,
		&i.Volume,
		&i.CreatedAt,
	)
	return i, err
}

const insertCandleH1 = `-- name: InsertCandleH1 :one
INSERT INTO candles_h1 (timestamp_utc, open, high, low, close, volume)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (timestamp_utc) DO UPDATE SET
    open = EXCLUDED.open,
    high = EXCLUDED.high,
    low = EXCLUDED.low,
    close = EXCLUDED.close,
    volume = EXCLUDED.volume
RETURNING id, timestamp_utc, open, high, low, close, volume, created_at
`

type InsertCandleH1Params struct {
	TimestampUtc pgtype.Timestamptz `json:"timestamp_utc"`
	Open         decimal.Decimal    `json:"open"`
	High         decimal.Decimal    `json:"high"`
	Low          decimal.Decimal    `json:"low"`
	Close        decimal.Decimal    `json:"close"`
	Volume       pgtype.Int8        `json:"volume"`
}

func (q *Queries) InsertCandleH1(ctx context.Context, arg InsertCandleH1Params) (CandlesH1, error) {
	row := q.db.QueryRow(ctx, insertCandleH1,
		arg.TimestampUtc,
		arg.Open,
		arg.High,
		arg.Low,
		arg.Close,
		arg.Volume,
	)
	var i CandlesH1
	err := row.Scan(
		&i.ID,
		&i.TimestampUtc,
		&i.Open,
		&i.High,
		&i.Low,
		&i.Close,
		&i.Volume,
		&i.CreatedAt,
	)
	return i, err
}

const insertCandleH4 = `-- name: InsertCandleH4 :one
INSERT INTO candles_h4 (timestamp_utc, open, high, low, close, volume)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (timestamp_utc) DO UPDATE SET
    open = EXCLUDED.open,
    high = EXCLUDED.high,
    low = EXCLUDED.low,
    close = EXCLUDED.close,
    volume = EXCLUDED.volume
RETURNING id, timestamp_utc, open, high, low, close, volume, created_at
`

type InsertCandleH4Params struct {
	TimestampUtc pgtype.Timestamptz `json:"timestamp_utc"`
	Open         decimal.Decimal    `json:"open"`
	High         decimal.Decimal    `json:"high"`
	Low          decimal.Decimal    `json:"low"`
	Close        decimal.Decimal    `json:"close"`
	Volume       pgtype.Int8        `json:"volume"`
}

func (q *Queries) InsertCandleH4(ctx context.Context, arg InsertCandleH4Params) (CandlesH4, error) {
	row := q.db.QueryRow(ctx, insertCandleH4,
		arg.TimestampUtc,
		arg.Open,
		arg.High,
		arg.Low,
		arg.Close,
		arg.Volume,
	)
	var i CandlesH4
	err := row.Scan(
		&i.ID,
		&i.TimestampUtc,
		&i.Open,
		&i.High,
		&i.Low,
		&i.Close,
		&i.Volume,
		&i.CreatedAt,
	)
	return i, err
}
