// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: candles.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createCandle = `-- name: CreateCandle :one
INSERT INTO candles_weekly (
    id,
    timestamp_utc,
    open,
    high,
    low,
    close,
    volume
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, timestamp_utc, open, high, low, close, volume, created_at
`

type CreateCandleParams struct {
	ID           uuid.UUID          `json:"id"`
	TimestampUtc pgtype.Timestamptz `json:"timestamp_utc"`
	Open         decimal.Decimal    `json:"open"`
	High         decimal.Decimal    `json:"high"`
	Low          decimal.Decimal    `json:"low"`
	Close        decimal.Decimal    `json:"close"`
	Volume       pgtype.Int8        `json:"volume"`
}

func (q *Queries) CreateCandle(ctx context.Context, arg CreateCandleParams) (CandlesWeekly, error) {
	row := q.db.QueryRow(ctx, createCandle,
		arg.ID,
		arg.TimestampUtc,
		arg.Open,
		arg.High,
		arg.Low,
		arg.Close,
		arg.Volume,
	)
	var i CandlesWeekly
	err := row.Scan(
		&i.ID,
		&i.TimestampUtc,
		&i.Open,
		&i.High,
		&i.Low,
		&i.Close,
		&i.Volume,
		&i.CreatedAt,
	)
	return i, err
}

const getAllCandlesOrdered = `-- name: GetAllCandlesOrdered :many
SELECT id, timestamp_utc, open, high, low, close, volume, created_at FROM candles_weekly 
ORDER BY timestamp_utc ASC
`

func (q *Queries) GetAllCandlesOrdered(ctx context.Context) ([]CandlesWeekly, error) {
	rows, err := q.db.Query(ctx, getAllCandlesOrdered)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CandlesWeekly
	for rows.Next() {
		var i CandlesWeekly
		if err := rows.Scan(
			&i.ID,
			&i.TimestampUtc,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCandleByID = `-- name: GetCandleByID :one
SELECT id, timestamp_utc, open, high, low, close, volume, created_at FROM candles_weekly 
WHERE id = $1
`

func (q *Queries) GetCandleByID(ctx context.Context, id uuid.UUID) (CandlesWeekly, error) {
	row := q.db.QueryRow(ctx, getCandleByID, id)
	var i CandlesWeekly
	err := row.Scan(
		&i.ID,
		&i.TimestampUtc,
		&i.Open,
		&i.High,
		&i.Low,
		&i.Close,
		&i.Volume,
		&i.CreatedAt,
	)
	return i, err
}

const getCandleByTimestamp = `-- name: GetCandleByTimestamp :one
SELECT id, timestamp_utc, open, high, low, close, volume, created_at FROM candles_weekly 
WHERE timestamp_utc = $1
`

func (q *Queries) GetCandleByTimestamp(ctx context.Context, timestampUtc pgtype.Timestamptz) (CandlesWeekly, error) {
	row := q.db.QueryRow(ctx, getCandleByTimestamp, timestampUtc)
	var i CandlesWeekly
	err := row.Scan(
		&i.ID,
		&i.TimestampUtc,
		&i.Open,
		&i.High,
		&i.Low,
		&i.Close,
		&i.Volume,
		&i.CreatedAt,
	)
	return i, err
}

const getCandlesInRange = `-- name: GetCandlesInRange :many
SELECT id, timestamp_utc, open, high, low, close, volume, created_at FROM candles_weekly 
WHERE timestamp_utc BETWEEN $1 AND $2
ORDER BY timestamp_utc ASC
`

type GetCandlesInRangeParams struct {
	TimestampUtc   pgtype.Timestamptz `json:"timestamp_utc"`
	TimestampUtc_2 pgtype.Timestamptz `json:"timestamp_utc_2"`
}

func (q *Queries) GetCandlesInRange(ctx context.Context, arg GetCandlesInRangeParams) ([]CandlesWeekly, error) {
	rows, err := q.db.Query(ctx, getCandlesInRange, arg.TimestampUtc, arg.TimestampUtc_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CandlesWeekly
	for rows.Next() {
		var i CandlesWeekly
		if err := rows.Scan(
			&i.ID,
			&i.TimestampUtc,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestCandles = `-- name: GetLatestCandles :many
SELECT id, timestamp_utc, open, high, low, close, volume, created_at FROM candles_weekly 
ORDER BY timestamp_utc DESC
LIMIT $1
`

func (q *Queries) GetLatestCandles(ctx context.Context, limit int32) ([]CandlesWeekly, error) {
	rows, err := q.db.Query(ctx, getLatestCandles, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CandlesWeekly
	for rows.Next() {
		var i CandlesWeekly
		if err := rows.Scan(
			&i.ID,
			&i.TimestampUtc,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIndicatorEMAs = `-- name: UpdateIndicatorEMAs :exec
UPDATE indicators_weekly 
SET 
    ema20 = $2,
    ema50 = $3,
    ema200 = $4
WHERE id = $1
`

type UpdateIndicatorEMAsParams struct {
	ID     uuid.UUID       `json:"id"`
	Ema20  decimal.Decimal `json:"ema20"`
	Ema50  decimal.Decimal `json:"ema50"`
	Ema200 decimal.Decimal `json:"ema200"`
}

func (q *Queries) UpdateIndicatorEMAs(ctx context.Context, arg UpdateIndicatorEMAsParams) error {
	_, err := q.db.Exec(ctx, updateIndicatorEMAs,
		arg.ID,
		arg.Ema20,
		arg.Ema50,
		arg.Ema200,
	)
	return err
}
