// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: candles.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCandle = `-- name: CreateCandle :one
INSERT INTO candles_weekly (
  id, timestamp_utc, open, high, low, close, volume
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, timestamp_utc, open, high, low, close, volume, created_at
`

type CreateCandleParams struct {
	ID           uuid.UUID          `json:"id"`
	TimestampUtc pgtype.Timestamptz `json:"timestamp_utc"`
	Open         pgtype.Numeric     `json:"open"`
	High         pgtype.Numeric     `json:"high"`
	Low          pgtype.Numeric     `json:"low"`
	Close        pgtype.Numeric     `json:"close"`
	Volume       pgtype.Int8        `json:"volume"`
}

func (q *Queries) CreateCandle(ctx context.Context, arg CreateCandleParams) (CandlesWeekly, error) {
	row := q.db.QueryRow(ctx, createCandle,
		arg.ID,
		arg.TimestampUtc,
		arg.Open,
		arg.High,
		arg.Low,
		arg.Close,
		arg.Volume,
	)
	var i CandlesWeekly
	err := row.Scan(
		&i.ID,
		&i.TimestampUtc,
		&i.Open,
		&i.High,
		&i.Low,
		&i.Close,
		&i.Volume,
		&i.CreatedAt,
	)
	return i, err
}

const getCandles = `-- name: GetCandles :many
SELECT id, timestamp_utc, open, high, low, close, volume, created_at FROM candles_weekly 
WHERE timestamp_utc >= $1 AND timestamp_utc <= $2 
ORDER BY timestamp_utc DESC
LIMIT $3
`

type GetCandlesParams struct {
	TimestampUtc   pgtype.Timestamptz `json:"timestamp_utc"`
	TimestampUtc_2 pgtype.Timestamptz `json:"timestamp_utc_2"`
	Limit          int32              `json:"limit"`
}

func (q *Queries) GetCandles(ctx context.Context, arg GetCandlesParams) ([]CandlesWeekly, error) {
	rows, err := q.db.Query(ctx, getCandles, arg.TimestampUtc, arg.TimestampUtc_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CandlesWeekly
	for rows.Next() {
		var i CandlesWeekly
		if err := rows.Scan(
			&i.ID,
			&i.TimestampUtc,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
			&i.Volume,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
