// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: indicators_multi_tf.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getIndicatorD1ByCandleID = `-- name: GetIndicatorD1ByCandleID :one
SELECT id, candle_id, ema20, ema50, ema200, range_size, body_size, upper_wick, lower_wick, mid_price, last_swing_high_price, last_swing_low_price, computed_at FROM indicators_d1 WHERE candle_id = $1
`

func (q *Queries) GetIndicatorD1ByCandleID(ctx context.Context, candleID uuid.UUID) (IndicatorsD1, error) {
	row := q.db.QueryRow(ctx, getIndicatorD1ByCandleID, candleID)
	var i IndicatorsD1
	err := row.Scan(
		&i.ID,
		&i.CandleID,
		&i.Ema20,
		&i.Ema50,
		&i.Ema200,
		&i.RangeSize,
		&i.BodySize,
		&i.UpperWick,
		&i.LowerWick,
		&i.MidPrice,
		&i.LastSwingHighPrice,
		&i.LastSwingLowPrice,
		&i.ComputedAt,
	)
	return i, err
}

const getIndicatorH1ByCandleID = `-- name: GetIndicatorH1ByCandleID :one
SELECT id, candle_id, ema20, ema50, ema200, range_size, body_size, upper_wick, lower_wick, mid_price, last_swing_high_price, last_swing_low_price, computed_at FROM indicators_h1 WHERE candle_id = $1
`

func (q *Queries) GetIndicatorH1ByCandleID(ctx context.Context, candleID uuid.UUID) (IndicatorsH1, error) {
	row := q.db.QueryRow(ctx, getIndicatorH1ByCandleID, candleID)
	var i IndicatorsH1
	err := row.Scan(
		&i.ID,
		&i.CandleID,
		&i.Ema20,
		&i.Ema50,
		&i.Ema200,
		&i.RangeSize,
		&i.BodySize,
		&i.UpperWick,
		&i.LowerWick,
		&i.MidPrice,
		&i.LastSwingHighPrice,
		&i.LastSwingLowPrice,
		&i.ComputedAt,
	)
	return i, err
}

const getIndicatorH4ByCandleID = `-- name: GetIndicatorH4ByCandleID :one
SELECT id, candle_id, ema20, ema50, ema200, range_size, body_size, upper_wick, lower_wick, mid_price, last_swing_high_price, last_swing_low_price, computed_at FROM indicators_h4 WHERE candle_id = $1
`

func (q *Queries) GetIndicatorH4ByCandleID(ctx context.Context, candleID uuid.UUID) (IndicatorsH4, error) {
	row := q.db.QueryRow(ctx, getIndicatorH4ByCandleID, candleID)
	var i IndicatorsH4
	err := row.Scan(
		&i.ID,
		&i.CandleID,
		&i.Ema20,
		&i.Ema50,
		&i.Ema200,
		&i.RangeSize,
		&i.BodySize,
		&i.UpperWick,
		&i.LowerWick,
		&i.MidPrice,
		&i.LastSwingHighPrice,
		&i.LastSwingLowPrice,
		&i.ComputedAt,
	)
	return i, err
}

const insertIndicatorD1 = `-- name: InsertIndicatorD1 :one
INSERT INTO indicators_d1 (
    candle_id, ema20, ema50, ema200,
    range_size, body_size, upper_wick, lower_wick,
    mid_price, last_swing_high_price, last_swing_low_price
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (candle_id) DO UPDATE SET
    ema20 = EXCLUDED.ema20,
    ema50 = EXCLUDED.ema50,
    ema200 = EXCLUDED.ema200,
    range_size = EXCLUDED.range_size,
    body_size = EXCLUDED.body_size,
    upper_wick = EXCLUDED.upper_wick,
    lower_wick = EXCLUDED.lower_wick,
    mid_price = EXCLUDED.mid_price,
    last_swing_high_price = EXCLUDED.last_swing_high_price,
    last_swing_low_price = EXCLUDED.last_swing_low_price
RETURNING id, candle_id, ema20, ema50, ema200, range_size, body_size, upper_wick, lower_wick, mid_price, last_swing_high_price, last_swing_low_price, computed_at
`

type InsertIndicatorD1Params struct {
	CandleID           uuid.UUID       `json:"candle_id"`
	Ema20              decimal.Decimal `json:"ema20"`
	Ema50              decimal.Decimal `json:"ema50"`
	Ema200             decimal.Decimal `json:"ema200"`
	RangeSize          decimal.Decimal `json:"range_size"`
	BodySize           decimal.Decimal `json:"body_size"`
	UpperWick          decimal.Decimal `json:"upper_wick"`
	LowerWick          decimal.Decimal `json:"lower_wick"`
	MidPrice           decimal.Decimal `json:"mid_price"`
	LastSwingHighPrice decimal.Decimal `json:"last_swing_high_price"`
	LastSwingLowPrice  decimal.Decimal `json:"last_swing_low_price"`
}

func (q *Queries) InsertIndicatorD1(ctx context.Context, arg InsertIndicatorD1Params) (IndicatorsD1, error) {
	row := q.db.QueryRow(ctx, insertIndicatorD1,
		arg.CandleID,
		arg.Ema20,
		arg.Ema50,
		arg.Ema200,
		arg.RangeSize,
		arg.BodySize,
		arg.UpperWick,
		arg.LowerWick,
		arg.MidPrice,
		arg.LastSwingHighPrice,
		arg.LastSwingLowPrice,
	)
	var i IndicatorsD1
	err := row.Scan(
		&i.ID,
		&i.CandleID,
		&i.Ema20,
		&i.Ema50,
		&i.Ema200,
		&i.RangeSize,
		&i.BodySize,
		&i.UpperWick,
		&i.LowerWick,
		&i.MidPrice,
		&i.LastSwingHighPrice,
		&i.LastSwingLowPrice,
		&i.ComputedAt,
	)
	return i, err
}

const insertIndicatorH1 = `-- name: InsertIndicatorH1 :one
INSERT INTO indicators_h1 (
    candle_id, ema20, ema50, ema200,
    range_size, body_size, upper_wick, lower_wick,
    mid_price, last_swing_high_price, last_swing_low_price
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (candle_id) DO UPDATE SET
    ema20 = EXCLUDED.ema20,
    ema50 = EXCLUDED.ema50,
    ema200 = EXCLUDED.ema200,
    range_size = EXCLUDED.range_size,
    body_size = EXCLUDED.body_size,
    upper_wick = EXCLUDED.upper_wick,
    lower_wick = EXCLUDED.lower_wick,
    mid_price = EXCLUDED.mid_price,
    last_swing_high_price = EXCLUDED.last_swing_high_price,
    last_swing_low_price = EXCLUDED.last_swing_low_price
RETURNING id, candle_id, ema20, ema50, ema200, range_size, body_size, upper_wick, lower_wick, mid_price, last_swing_high_price, last_swing_low_price, computed_at
`

type InsertIndicatorH1Params struct {
	CandleID           uuid.UUID       `json:"candle_id"`
	Ema20              decimal.Decimal `json:"ema20"`
	Ema50              decimal.Decimal `json:"ema50"`
	Ema200             decimal.Decimal `json:"ema200"`
	RangeSize          decimal.Decimal `json:"range_size"`
	BodySize           decimal.Decimal `json:"body_size"`
	UpperWick          decimal.Decimal `json:"upper_wick"`
	LowerWick          decimal.Decimal `json:"lower_wick"`
	MidPrice           decimal.Decimal `json:"mid_price"`
	LastSwingHighPrice decimal.Decimal `json:"last_swing_high_price"`
	LastSwingLowPrice  decimal.Decimal `json:"last_swing_low_price"`
}

func (q *Queries) InsertIndicatorH1(ctx context.Context, arg InsertIndicatorH1Params) (IndicatorsH1, error) {
	row := q.db.QueryRow(ctx, insertIndicatorH1,
		arg.CandleID,
		arg.Ema20,
		arg.Ema50,
		arg.Ema200,
		arg.RangeSize,
		arg.BodySize,
		arg.UpperWick,
		arg.LowerWick,
		arg.MidPrice,
		arg.LastSwingHighPrice,
		arg.LastSwingLowPrice,
	)
	var i IndicatorsH1
	err := row.Scan(
		&i.ID,
		&i.CandleID,
		&i.Ema20,
		&i.Ema50,
		&i.Ema200,
		&i.RangeSize,
		&i.BodySize,
		&i.UpperWick,
		&i.LowerWick,
		&i.MidPrice,
		&i.LastSwingHighPrice,
		&i.LastSwingLowPrice,
		&i.ComputedAt,
	)
	return i, err
}

const insertIndicatorH4 = `-- name: InsertIndicatorH4 :one
INSERT INTO indicators_h4 (
    candle_id, ema20, ema50, ema200,
    range_size, body_size, upper_wick, lower_wick,
    mid_price, last_swing_high_price, last_swing_low_price
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (candle_id) DO UPDATE SET
    ema20 = EXCLUDED.ema20,
    ema50 = EXCLUDED.ema50,
    ema200 = EXCLUDED.ema200,
    range_size = EXCLUDED.range_size,
    body_size = EXCLUDED.body_size,
    upper_wick = EXCLUDED.upper_wick,
    lower_wick = EXCLUDED.lower_wick,
    mid_price = EXCLUDED.mid_price,
    last_swing_high_price = EXCLUDED.last_swing_high_price,
    last_swing_low_price = EXCLUDED.last_swing_low_price
RETURNING id, candle_id, ema20, ema50, ema200, range_size, body_size, upper_wick, lower_wick, mid_price, last_swing_high_price, last_swing_low_price, computed_at
`

type InsertIndicatorH4Params struct {
	CandleID           uuid.UUID       `json:"candle_id"`
	Ema20              decimal.Decimal `json:"ema20"`
	Ema50              decimal.Decimal `json:"ema50"`
	Ema200             decimal.Decimal `json:"ema200"`
	RangeSize          decimal.Decimal `json:"range_size"`
	BodySize           decimal.Decimal `json:"body_size"`
	UpperWick          decimal.Decimal `json:"upper_wick"`
	LowerWick          decimal.Decimal `json:"lower_wick"`
	MidPrice           decimal.Decimal `json:"mid_price"`
	LastSwingHighPrice decimal.Decimal `json:"last_swing_high_price"`
	LastSwingLowPrice  decimal.Decimal `json:"last_swing_low_price"`
}

func (q *Queries) InsertIndicatorH4(ctx context.Context, arg InsertIndicatorH4Params) (IndicatorsH4, error) {
	row := q.db.QueryRow(ctx, insertIndicatorH4,
		arg.CandleID,
		arg.Ema20,
		arg.Ema50,
		arg.Ema200,
		arg.RangeSize,
		arg.BodySize,
		arg.UpperWick,
		arg.LowerWick,
		arg.MidPrice,
		arg.LastSwingHighPrice,
		arg.LastSwingLowPrice,
	)
	var i IndicatorsH4
	err := row.Scan(
		&i.ID,
		&i.CandleID,
		&i.Ema20,
		&i.Ema50,
		&i.Ema200,
		&i.RangeSize,
		&i.BodySize,
		&i.UpperWick,
		&i.LowerWick,
		&i.MidPrice,
		&i.LastSwingHighPrice,
		&i.LastSwingLowPrice,
		&i.ComputedAt,
	)
	return i, err
}
