// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: indicators.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createIndicator = `-- name: CreateIndicator :one
INSERT INTO indicators_weekly (
    id,
    candle_id,
    ema20,
    ema50,
    ema200,
    range_size,
    body_size,
    upper_wick,
    lower_wick,
    mid_price,
    last_swing_high_price,
    last_swing_low_price
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, candle_id, ema20, ema50, ema200, range_size, body_size, upper_wick, lower_wick, mid_price, last_swing_high_price, last_swing_low_price, computed_at
`

type CreateIndicatorParams struct {
	ID                 uuid.UUID       `json:"id"`
	CandleID           uuid.UUID       `json:"candle_id"`
	Ema20              decimal.Decimal `json:"ema20"`
	Ema50              decimal.Decimal `json:"ema50"`
	Ema200             decimal.Decimal `json:"ema200"`
	RangeSize          decimal.Decimal `json:"range_size"`
	BodySize           decimal.Decimal `json:"body_size"`
	UpperWick          decimal.Decimal `json:"upper_wick"`
	LowerWick          decimal.Decimal `json:"lower_wick"`
	MidPrice           decimal.Decimal `json:"mid_price"`
	LastSwingHighPrice decimal.Decimal `json:"last_swing_high_price"`
	LastSwingLowPrice  decimal.Decimal `json:"last_swing_low_price"`
}

func (q *Queries) CreateIndicator(ctx context.Context, arg CreateIndicatorParams) (IndicatorsWeekly, error) {
	row := q.db.QueryRow(ctx, createIndicator,
		arg.ID,
		arg.CandleID,
		arg.Ema20,
		arg.Ema50,
		arg.Ema200,
		arg.RangeSize,
		arg.BodySize,
		arg.UpperWick,
		arg.LowerWick,
		arg.MidPrice,
		arg.LastSwingHighPrice,
		arg.LastSwingLowPrice,
	)
	var i IndicatorsWeekly
	err := row.Scan(
		&i.ID,
		&i.CandleID,
		&i.Ema20,
		&i.Ema50,
		&i.Ema200,
		&i.RangeSize,
		&i.BodySize,
		&i.UpperWick,
		&i.LowerWick,
		&i.MidPrice,
		&i.LastSwingHighPrice,
		&i.LastSwingLowPrice,
		&i.ComputedAt,
	)
	return i, err
}

const getIndicatorByCandleID = `-- name: GetIndicatorByCandleID :one
SELECT id, candle_id, ema20, ema50, ema200, range_size, body_size, upper_wick, lower_wick, mid_price, last_swing_high_price, last_swing_low_price, computed_at FROM indicators_weekly 
WHERE candle_id = $1
`

func (q *Queries) GetIndicatorByCandleID(ctx context.Context, candleID uuid.UUID) (IndicatorsWeekly, error) {
	row := q.db.QueryRow(ctx, getIndicatorByCandleID, candleID)
	var i IndicatorsWeekly
	err := row.Scan(
		&i.ID,
		&i.CandleID,
		&i.Ema20,
		&i.Ema50,
		&i.Ema200,
		&i.RangeSize,
		&i.BodySize,
		&i.UpperWick,
		&i.LowerWick,
		&i.MidPrice,
		&i.LastSwingHighPrice,
		&i.LastSwingLowPrice,
		&i.ComputedAt,
	)
	return i, err
}

const getLatestIndicators = `-- name: GetLatestIndicators :many
SELECT 
    i.id, i.candle_id, i.ema20, i.ema50, i.ema200, i.range_size, i.body_size, i.upper_wick, i.lower_wick, i.mid_price, i.last_swing_high_price, i.last_swing_low_price, i.computed_at,
    c.timestamp_utc,
    c.open,
    c.high,
    c.low,
    c.close
FROM indicators_weekly i
JOIN candles_weekly c ON i.candle_id = c.id
ORDER BY c.timestamp_utc DESC
LIMIT $1
`

type GetLatestIndicatorsRow struct {
	ID                 uuid.UUID          `json:"id"`
	CandleID           uuid.UUID          `json:"candle_id"`
	Ema20              decimal.Decimal    `json:"ema20"`
	Ema50              decimal.Decimal    `json:"ema50"`
	Ema200             decimal.Decimal    `json:"ema200"`
	RangeSize          decimal.Decimal    `json:"range_size"`
	BodySize           decimal.Decimal    `json:"body_size"`
	UpperWick          decimal.Decimal    `json:"upper_wick"`
	LowerWick          decimal.Decimal    `json:"lower_wick"`
	MidPrice           decimal.Decimal    `json:"mid_price"`
	LastSwingHighPrice decimal.Decimal    `json:"last_swing_high_price"`
	LastSwingLowPrice  decimal.Decimal    `json:"last_swing_low_price"`
	ComputedAt         pgtype.Timestamptz `json:"computed_at"`
	TimestampUtc       pgtype.Timestamptz `json:"timestamp_utc"`
	Open               decimal.Decimal    `json:"open"`
	High               decimal.Decimal    `json:"high"`
	Low                decimal.Decimal    `json:"low"`
	Close              decimal.Decimal    `json:"close"`
}

func (q *Queries) GetLatestIndicators(ctx context.Context, limit int32) ([]GetLatestIndicatorsRow, error) {
	rows, err := q.db.Query(ctx, getLatestIndicators, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestIndicatorsRow
	for rows.Next() {
		var i GetLatestIndicatorsRow
		if err := rows.Scan(
			&i.ID,
			&i.CandleID,
			&i.Ema20,
			&i.Ema50,
			&i.Ema200,
			&i.RangeSize,
			&i.BodySize,
			&i.UpperWick,
			&i.LowerWick,
			&i.MidPrice,
			&i.LastSwingHighPrice,
			&i.LastSwingLowPrice,
			&i.ComputedAt,
			&i.TimestampUtc,
			&i.Open,
			&i.High,
			&i.Low,
			&i.Close,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPreviousIndicatorByTimestamp = `-- name: GetPreviousIndicatorByTimestamp :one
SELECT i.id, candle_id, ema20, ema50, ema200, range_size, body_size, upper_wick, lower_wick, mid_price, last_swing_high_price, last_swing_low_price, computed_at, c.id, timestamp_utc, open, high, low, close, volume, created_at FROM indicators_weekly i
JOIN candles_weekly c ON i.candle_id = c.id
WHERE c.timestamp_utc < $1
ORDER BY c.timestamp_utc DESC
LIMIT 1
`

type GetPreviousIndicatorByTimestampRow struct {
	ID                 uuid.UUID          `json:"id"`
	CandleID           uuid.UUID          `json:"candle_id"`
	Ema20              decimal.Decimal    `json:"ema20"`
	Ema50              decimal.Decimal    `json:"ema50"`
	Ema200             decimal.Decimal    `json:"ema200"`
	RangeSize          decimal.Decimal    `json:"range_size"`
	BodySize           decimal.Decimal    `json:"body_size"`
	UpperWick          decimal.Decimal    `json:"upper_wick"`
	LowerWick          decimal.Decimal    `json:"lower_wick"`
	MidPrice           decimal.Decimal    `json:"mid_price"`
	LastSwingHighPrice decimal.Decimal    `json:"last_swing_high_price"`
	LastSwingLowPrice  decimal.Decimal    `json:"last_swing_low_price"`
	ComputedAt         pgtype.Timestamptz `json:"computed_at"`
	ID_2               uuid.UUID          `json:"id_2"`
	TimestampUtc       pgtype.Timestamptz `json:"timestamp_utc"`
	Open               decimal.Decimal    `json:"open"`
	High               decimal.Decimal    `json:"high"`
	Low                decimal.Decimal    `json:"low"`
	Close              decimal.Decimal    `json:"close"`
	Volume             pgtype.Int8        `json:"volume"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetPreviousIndicatorByTimestamp(ctx context.Context, timestampUtc pgtype.Timestamptz) (GetPreviousIndicatorByTimestampRow, error) {
	row := q.db.QueryRow(ctx, getPreviousIndicatorByTimestamp, timestampUtc)
	var i GetPreviousIndicatorByTimestampRow
	err := row.Scan(
		&i.ID,
		&i.CandleID,
		&i.Ema20,
		&i.Ema50,
		&i.Ema200,
		&i.RangeSize,
		&i.BodySize,
		&i.UpperWick,
		&i.LowerWick,
		&i.MidPrice,
		&i.LastSwingHighPrice,
		&i.LastSwingLowPrice,
		&i.ComputedAt,
		&i.ID_2,
		&i.TimestampUtc,
		&i.Open,
		&i.High,
		&i.Low,
		&i.Close,
		&i.Volume,
		&i.CreatedAt,
	)
	return i, err
}
