// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	BrokerName      string             `json:"broker_name"`
	AccountType     string             `json:"account_type"`
	Currency        pgtype.Text        `json:"currency"`
	Balance         float64            `json:"balance"`
	Leverage        pgtype.Text        `json:"leverage"`
	MaxRiskPerTrade pgtype.Float8      `json:"max_risk_per_trade"`
	MaxDailyRisk    pgtype.Float8      `json:"max_daily_risk"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Candle struct {
	ID        uuid.UUID          `json:"id"`
	Symbol    string             `json:"symbol"`
	Timeframe string             `json:"timeframe"`
	Timestamp time.Time          `json:"timestamp"`
	Open      float64            `json:"open"`
	High      float64            `json:"high"`
	Low       float64            `json:"low"`
	Close     float64            `json:"close"`
	Volume    pgtype.Int8        `json:"volume"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	Username  string             `json:"username"`
	Password  string             `json:"password"`
	Timezone  pgtype.Text        `json:"timezone"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
