// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type AccountType string

const (
	AccountTypeDemo AccountType = "demo"
	AccountTypeLive AccountType = "live"
)

func (e *AccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountType(s)
	case string:
		*e = AccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountType: %T", src)
	}
	return nil
}

type NullAccountType struct {
	AccountType AccountType `json:"account_type"`
	Valid       bool        `json:"valid"` // Valid is true if AccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.AccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountType), nil
}

type ExecutionType string

const (
	ExecutionTypeENTRYFILLED ExecutionType = "ENTRY_FILLED"
	ExecutionTypePARTIALEXIT ExecutionType = "PARTIAL_EXIT"
	ExecutionTypeTPHIT       ExecutionType = "TP_HIT"
	ExecutionTypeSLHIT       ExecutionType = "SL_HIT"
	ExecutionTypeMANUALCLOSE ExecutionType = "MANUAL_CLOSE"
)

func (e *ExecutionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExecutionType(s)
	case string:
		*e = ExecutionType(s)
	default:
		return fmt.Errorf("unsupported scan type for ExecutionType: %T", src)
	}
	return nil
}

type NullExecutionType struct {
	ExecutionType ExecutionType `json:"execution_type"`
	Valid         bool          `json:"valid"` // Valid is true if ExecutionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExecutionType) Scan(value interface{}) error {
	if value == nil {
		ns.ExecutionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExecutionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExecutionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExecutionType), nil
}

type RuleResultType string

const (
	RuleResultTypePASS RuleResultType = "PASS"
	RuleResultTypeFAIL RuleResultType = "FAIL"
)

func (e *RuleResultType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RuleResultType(s)
	case string:
		*e = RuleResultType(s)
	default:
		return fmt.Errorf("unsupported scan type for RuleResultType: %T", src)
	}
	return nil
}

type NullRuleResultType struct {
	RuleResultType RuleResultType `json:"rule_result_type"`
	Valid          bool           `json:"valid"` // Valid is true if RuleResultType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRuleResultType) Scan(value interface{}) error {
	if value == nil {
		ns.RuleResultType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RuleResultType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRuleResultType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RuleResultType), nil
}

type RuleTimeframe string

const (
	RuleTimeframeW1 RuleTimeframe = "W1"
)

func (e *RuleTimeframe) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RuleTimeframe(s)
	case string:
		*e = RuleTimeframe(s)
	default:
		return fmt.Errorf("unsupported scan type for RuleTimeframe: %T", src)
	}
	return nil
}

type NullRuleTimeframe struct {
	RuleTimeframe RuleTimeframe `json:"rule_timeframe"`
	Valid         bool          `json:"valid"` // Valid is true if RuleTimeframe is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRuleTimeframe) Scan(value interface{}) error {
	if value == nil {
		ns.RuleTimeframe, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RuleTimeframe.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRuleTimeframe) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RuleTimeframe), nil
}

type SessionType string

const (
	SessionTypeLondon  SessionType = "london"
	SessionTypeNewYork SessionType = "new_york"
	SessionTypeAsian   SessionType = "asian"
	SessionTypeCustom  SessionType = "custom"
)

func (e *SessionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionType(s)
	case string:
		*e = SessionType(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionType: %T", src)
	}
	return nil
}

type NullSessionType struct {
	SessionType SessionType `json:"session_type"`
	Valid       bool        `json:"valid"` // Valid is true if SessionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionType) Scan(value interface{}) error {
	if value == nil {
		ns.SessionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionType), nil
}

type TradeDirection string

const (
	TradeDirectionLONG  TradeDirection = "LONG"
	TradeDirectionSHORT TradeDirection = "SHORT"
)

func (e *TradeDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TradeDirection(s)
	case string:
		*e = TradeDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for TradeDirection: %T", src)
	}
	return nil
}

type NullTradeDirection struct {
	TradeDirection TradeDirection `json:"trade_direction"`
	Valid          bool           `json:"valid"` // Valid is true if TradeDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTradeDirection) Scan(value interface{}) error {
	if value == nil {
		ns.TradeDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TradeDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTradeDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TradeDirection), nil
}

type Account struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	Type               AccountType        `json:"type"`
	BrokerName         string             `json:"broker_name"`
	Currency           string             `json:"currency"`
	Balance            decimal.Decimal    `json:"balance"`
	Leverage           int32              `json:"leverage"`
	MaxRiskPerTradePct decimal.Decimal    `json:"max_risk_per_trade_pct"`
	MaxDailyRiskPct    decimal.Decimal    `json:"max_daily_risk_pct"`
	Timezone           string             `json:"timezone"`
	PreferredSession   SessionType        `json:"preferred_session"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type CandlesWeekly struct {
	ID           uuid.UUID          `json:"id"`
	TimestampUtc pgtype.Timestamptz `json:"timestamp_utc"`
	Open         decimal.Decimal    `json:"open"`
	High         decimal.Decimal    `json:"high"`
	Low          decimal.Decimal    `json:"low"`
	Close        decimal.Decimal    `json:"close"`
	Volume       pgtype.Int8        `json:"volume"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type IndicatorsWeekly struct {
	ID                 uuid.UUID          `json:"id"`
	CandleID           uuid.UUID          `json:"candle_id"`
	Ema20              decimal.Decimal    `json:"ema20"`
	Ema50              decimal.Decimal    `json:"ema50"`
	Ema200             decimal.Decimal    `json:"ema200"`
	RangeSize          decimal.Decimal    `json:"range_size"`
	BodySize           decimal.Decimal    `json:"body_size"`
	UpperWick          decimal.Decimal    `json:"upper_wick"`
	LowerWick          decimal.Decimal    `json:"lower_wick"`
	MidPrice           decimal.Decimal    `json:"mid_price"`
	LastSwingHighPrice decimal.Decimal    `json:"last_swing_high_price"`
	LastSwingLowPrice  decimal.Decimal    `json:"last_swing_low_price"`
	ComputedAt         pgtype.Timestamptz `json:"computed_at"`
}

type Rule struct {
	ID          uuid.UUID          `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Timeframe   RuleTimeframe      `json:"timeframe"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RuleResult struct {
	ID              uuid.UUID          `json:"id"`
	RuleID          uuid.UUID          `json:"rule_id"`
	CandleID        uuid.UUID          `json:"candle_id"`
	Result          RuleResultType     `json:"result"`
	EvaluatedAt     pgtype.Timestamptz `json:"evaluated_at"`
	ConfidenceScore decimal.Decimal    `json:"confidence_score"`
}

type Trade struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	AccountID    uuid.UUID          `json:"account_id"`
	CandleID     uuid.UUID          `json:"candle_id"`
	Symbol       string             `json:"symbol"`
	Timeframe    string             `json:"timeframe"`
	Direction    TradeDirection     `json:"direction"`
	PlannedEntry decimal.Decimal    `json:"planned_entry"`
	StopLoss     decimal.Decimal    `json:"stop_loss"`
	TakeProfit   decimal.Decimal    `json:"take_profit"`
	RiskPercent  decimal.Decimal    `json:"risk_percent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type TradeExecution struct {
	ID            uuid.UUID          `json:"id"`
	TradeID       uuid.UUID          `json:"trade_id"`
	ExecutionType ExecutionType      `json:"execution_type"`
	Price         decimal.Decimal    `json:"price"`
	Quantity      decimal.Decimal    `json:"quantity"`
	ExecutedAt    pgtype.Timestamptz `json:"executed_at"`
}

type User struct {
	ID        uuid.UUID          `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
