// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: patterns.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const countPatternDetections = `-- name: CountPatternDetections :one
SELECT COUNT(*) FROM pattern_detections 
WHERE symbol = $1 AND timeframe = $2
`

type CountPatternDetectionsParams struct {
	Symbol    string        `json:"symbol"`
	Timeframe RuleTimeframe `json:"timeframe"`
}

func (q *Queries) CountPatternDetections(ctx context.Context, arg CountPatternDetectionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPatternDetections, arg.Symbol, arg.Timeframe)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSignalsByStatus = `-- name: CountSignalsByStatus :one
SELECT COUNT(*) FROM signals WHERE status = $1
`

func (q *Queries) CountSignalsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countSignalsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPatternDetectionByID = `-- name: GetPatternDetectionByID :one
SELECT id, symbol, timeframe, detected_candle_idx, left_shoulder_price, left_shoulder_idx, head_price, head_idx, right_shoulder_price, right_shoulder_idx, neckline_price, neckline_idx, shoulder_symmetry, head_prominence, time_symmetry, volume_profile, neckline_quality, context_trend, volatility_regime, context_dist_ema200, recent_swings, overall_confidence, final_confidence, pattern_type, created_at FROM pattern_detections WHERE id = $1
`

func (q *Queries) GetPatternDetectionByID(ctx context.Context, id uuid.UUID) (PatternDetection, error) {
	row := q.db.QueryRow(ctx, getPatternDetectionByID, id)
	var i PatternDetection
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Timeframe,
		&i.DetectedCandleIdx,
		&i.LeftShoulderPrice,
		&i.LeftShoulderIdx,
		&i.HeadPrice,
		&i.HeadIdx,
		&i.RightShoulderPrice,
		&i.RightShoulderIdx,
		&i.NecklinePrice,
		&i.NecklineIdx,
		&i.ShoulderSymmetry,
		&i.HeadProminence,
		&i.TimeSymmetry,
		&i.VolumeProfile,
		&i.NecklineQuality,
		&i.ContextTrend,
		&i.VolatilityRegime,
		&i.ContextDistEma200,
		&i.RecentSwings,
		&i.OverallConfidence,
		&i.FinalConfidence,
		&i.PatternType,
		&i.CreatedAt,
	)
	return i, err
}

const getPatternDetectionsByConfidence = `-- name: GetPatternDetectionsByConfidence :many
SELECT id, symbol, timeframe, detected_candle_idx, left_shoulder_price, left_shoulder_idx, head_price, head_idx, right_shoulder_price, right_shoulder_idx, neckline_price, neckline_idx, shoulder_symmetry, head_prominence, time_symmetry, volume_profile, neckline_quality, context_trend, volatility_regime, context_dist_ema200, recent_swings, overall_confidence, final_confidence, pattern_type, created_at FROM pattern_detections 
WHERE symbol = $1 AND final_confidence >= $2
ORDER BY final_confidence DESC
LIMIT $3
`

type GetPatternDetectionsByConfidenceParams struct {
	Symbol          string          `json:"symbol"`
	FinalConfidence decimal.Decimal `json:"final_confidence"`
	Limit           int32           `json:"limit"`
}

func (q *Queries) GetPatternDetectionsByConfidence(ctx context.Context, arg GetPatternDetectionsByConfidenceParams) ([]PatternDetection, error) {
	rows, err := q.db.Query(ctx, getPatternDetectionsByConfidence, arg.Symbol, arg.FinalConfidence, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatternDetection
	for rows.Next() {
		var i PatternDetection
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Timeframe,
			&i.DetectedCandleIdx,
			&i.LeftShoulderPrice,
			&i.LeftShoulderIdx,
			&i.HeadPrice,
			&i.HeadIdx,
			&i.RightShoulderPrice,
			&i.RightShoulderIdx,
			&i.NecklinePrice,
			&i.NecklineIdx,
			&i.ShoulderSymmetry,
			&i.HeadProminence,
			&i.TimeSymmetry,
			&i.VolumeProfile,
			&i.NecklineQuality,
			&i.ContextTrend,
			&i.VolatilityRegime,
			&i.ContextDistEma200,
			&i.RecentSwings,
			&i.OverallConfidence,
			&i.FinalConfidence,
			&i.PatternType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPatternDetectionsByTimeframe = `-- name: GetPatternDetectionsByTimeframe :many
SELECT id, symbol, timeframe, detected_candle_idx, left_shoulder_price, left_shoulder_idx, head_price, head_idx, right_shoulder_price, right_shoulder_idx, neckline_price, neckline_idx, shoulder_symmetry, head_prominence, time_symmetry, volume_profile, neckline_quality, context_trend, volatility_regime, context_dist_ema200, recent_swings, overall_confidence, final_confidence, pattern_type, created_at FROM pattern_detections 
WHERE symbol = $1 AND timeframe = $2
ORDER BY created_at DESC
LIMIT $3
`

type GetPatternDetectionsByTimeframeParams struct {
	Symbol    string        `json:"symbol"`
	Timeframe RuleTimeframe `json:"timeframe"`
	Limit     int32         `json:"limit"`
}

func (q *Queries) GetPatternDetectionsByTimeframe(ctx context.Context, arg GetPatternDetectionsByTimeframeParams) ([]PatternDetection, error) {
	rows, err := q.db.Query(ctx, getPatternDetectionsByTimeframe, arg.Symbol, arg.Timeframe, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatternDetection
	for rows.Next() {
		var i PatternDetection
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Timeframe,
			&i.DetectedCandleIdx,
			&i.LeftShoulderPrice,
			&i.LeftShoulderIdx,
			&i.HeadPrice,
			&i.HeadIdx,
			&i.RightShoulderPrice,
			&i.RightShoulderIdx,
			&i.NecklinePrice,
			&i.NecklineIdx,
			&i.ShoulderSymmetry,
			&i.HeadProminence,
			&i.TimeSymmetry,
			&i.VolumeProfile,
			&i.NecklineQuality,
			&i.ContextTrend,
			&i.VolatilityRegime,
			&i.ContextDistEma200,
			&i.RecentSwings,
			&i.OverallConfidence,
			&i.FinalConfidence,
			&i.PatternType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSignalByID = `-- name: GetSignalByID :one
SELECT id, pattern_detection_id, symbol, timeframe, execution_timeframe, direction, detected_price, theoretical_sl, theoretical_tp, projected_rr, confidence, status, created_at FROM signals WHERE id = $1
`

func (q *Queries) GetSignalByID(ctx context.Context, id uuid.UUID) (Signal, error) {
	row := q.db.QueryRow(ctx, getSignalByID, id)
	var i Signal
	err := row.Scan(
		&i.ID,
		&i.PatternDetectionID,
		&i.Symbol,
		&i.Timeframe,
		&i.ExecutionTimeframe,
		&i.Direction,
		&i.DetectedPrice,
		&i.TheoreticalSl,
		&i.TheoreticalTp,
		&i.ProjectedRr,
		&i.Confidence,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getSignalsByPattern = `-- name: GetSignalsByPattern :many
SELECT id, pattern_detection_id, symbol, timeframe, execution_timeframe, direction, detected_price, theoretical_sl, theoretical_tp, projected_rr, confidence, status, created_at FROM signals 
WHERE pattern_detection_id = $1
`

func (q *Queries) GetSignalsByPattern(ctx context.Context, patternDetectionID uuid.UUID) ([]Signal, error) {
	rows, err := q.db.Query(ctx, getSignalsByPattern, patternDetectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Signal
	for rows.Next() {
		var i Signal
		if err := rows.Scan(
			&i.ID,
			&i.PatternDetectionID,
			&i.Symbol,
			&i.Timeframe,
			&i.ExecutionTimeframe,
			&i.Direction,
			&i.DetectedPrice,
			&i.TheoreticalSl,
			&i.TheoreticalTp,
			&i.ProjectedRr,
			&i.Confidence,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSignalsByStatus = `-- name: GetSignalsByStatus :many
SELECT id, pattern_detection_id, symbol, timeframe, execution_timeframe, direction, detected_price, theoretical_sl, theoretical_tp, projected_rr, confidence, status, created_at FROM signals 
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetSignalsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) GetSignalsByStatus(ctx context.Context, arg GetSignalsByStatusParams) ([]Signal, error) {
	rows, err := q.db.Query(ctx, getSignalsByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Signal
	for rows.Next() {
		var i Signal
		if err := rows.Scan(
			&i.ID,
			&i.PatternDetectionID,
			&i.Symbol,
			&i.Timeframe,
			&i.ExecutionTimeframe,
			&i.Direction,
			&i.DetectedPrice,
			&i.TheoreticalSl,
			&i.TheoreticalTp,
			&i.ProjectedRr,
			&i.Confidence,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPatternDetection = `-- name: InsertPatternDetection :one
INSERT INTO pattern_detections (
    symbol, timeframe, detected_candle_idx,
    left_shoulder_price, left_shoulder_idx,
    head_price, head_idx,
    right_shoulder_price, right_shoulder_idx,
    neckline_price, neckline_idx,
    shoulder_symmetry, head_prominence, time_symmetry,
    volume_profile, neckline_quality,
    context_trend, volatility_regime, context_dist_ema200, recent_swings,
    overall_confidence, final_confidence, pattern_type
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23
)
RETURNING id, symbol, timeframe, detected_candle_idx, left_shoulder_price, left_shoulder_idx, head_price, head_idx, right_shoulder_price, right_shoulder_idx, neckline_price, neckline_idx, shoulder_symmetry, head_prominence, time_symmetry, volume_profile, neckline_quality, context_trend, volatility_regime, context_dist_ema200, recent_swings, overall_confidence, final_confidence, pattern_type, created_at
`

type InsertPatternDetectionParams struct {
	Symbol             string          `json:"symbol"`
	Timeframe          RuleTimeframe   `json:"timeframe"`
	DetectedCandleIdx  int32           `json:"detected_candle_idx"`
	LeftShoulderPrice  decimal.Decimal `json:"left_shoulder_price"`
	LeftShoulderIdx    int32           `json:"left_shoulder_idx"`
	HeadPrice          decimal.Decimal `json:"head_price"`
	HeadIdx            int32           `json:"head_idx"`
	RightShoulderPrice decimal.Decimal `json:"right_shoulder_price"`
	RightShoulderIdx   int32           `json:"right_shoulder_idx"`
	NecklinePrice      decimal.Decimal `json:"neckline_price"`
	NecklineIdx        int32           `json:"neckline_idx"`
	ShoulderSymmetry   decimal.Decimal `json:"shoulder_symmetry"`
	HeadProminence     decimal.Decimal `json:"head_prominence"`
	TimeSymmetry       decimal.Decimal `json:"time_symmetry"`
	VolumeProfile      decimal.Decimal `json:"volume_profile"`
	NecklineQuality    decimal.Decimal `json:"neckline_quality"`
	ContextTrend       string          `json:"context_trend"`
	VolatilityRegime   string          `json:"volatility_regime"`
	ContextDistEma200  decimal.Decimal `json:"context_dist_ema200"`
	RecentSwings       int32           `json:"recent_swings"`
	OverallConfidence  decimal.Decimal `json:"overall_confidence"`
	FinalConfidence    decimal.Decimal `json:"final_confidence"`
	PatternType        string          `json:"pattern_type"`
}

func (q *Queries) InsertPatternDetection(ctx context.Context, arg InsertPatternDetectionParams) (PatternDetection, error) {
	row := q.db.QueryRow(ctx, insertPatternDetection,
		arg.Symbol,
		arg.Timeframe,
		arg.DetectedCandleIdx,
		arg.LeftShoulderPrice,
		arg.LeftShoulderIdx,
		arg.HeadPrice,
		arg.HeadIdx,
		arg.RightShoulderPrice,
		arg.RightShoulderIdx,
		arg.NecklinePrice,
		arg.NecklineIdx,
		arg.ShoulderSymmetry,
		arg.HeadProminence,
		arg.TimeSymmetry,
		arg.VolumeProfile,
		arg.NecklineQuality,
		arg.ContextTrend,
		arg.VolatilityRegime,
		arg.ContextDistEma200,
		arg.RecentSwings,
		arg.OverallConfidence,
		arg.FinalConfidence,
		arg.PatternType,
	)
	var i PatternDetection
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.Timeframe,
		&i.DetectedCandleIdx,
		&i.LeftShoulderPrice,
		&i.LeftShoulderIdx,
		&i.HeadPrice,
		&i.HeadIdx,
		&i.RightShoulderPrice,
		&i.RightShoulderIdx,
		&i.NecklinePrice,
		&i.NecklineIdx,
		&i.ShoulderSymmetry,
		&i.HeadProminence,
		&i.TimeSymmetry,
		&i.VolumeProfile,
		&i.NecklineQuality,
		&i.ContextTrend,
		&i.VolatilityRegime,
		&i.ContextDistEma200,
		&i.RecentSwings,
		&i.OverallConfidence,
		&i.FinalConfidence,
		&i.PatternType,
		&i.CreatedAt,
	)
	return i, err
}

const insertSignal = `-- name: InsertSignal :one
INSERT INTO signals (
    pattern_detection_id, symbol, timeframe, execution_timeframe,
    direction, detected_price, theoretical_sl, theoretical_tp,
    projected_rr, confidence, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, pattern_detection_id, symbol, timeframe, execution_timeframe, direction, detected_price, theoretical_sl, theoretical_tp, projected_rr, confidence, status, created_at
`

type InsertSignalParams struct {
	PatternDetectionID uuid.UUID       `json:"pattern_detection_id"`
	Symbol             string          `json:"symbol"`
	Timeframe          RuleTimeframe   `json:"timeframe"`
	ExecutionTimeframe RuleTimeframe   `json:"execution_timeframe"`
	Direction          TradeDirection  `json:"direction"`
	DetectedPrice      decimal.Decimal `json:"detected_price"`
	TheoreticalSl      decimal.Decimal `json:"theoretical_sl"`
	TheoreticalTp      decimal.Decimal `json:"theoretical_tp"`
	ProjectedRr        decimal.Decimal `json:"projected_rr"`
	Confidence         decimal.Decimal `json:"confidence"`
	Status             string          `json:"status"`
}

func (q *Queries) InsertSignal(ctx context.Context, arg InsertSignalParams) (Signal, error) {
	row := q.db.QueryRow(ctx, insertSignal,
		arg.PatternDetectionID,
		arg.Symbol,
		arg.Timeframe,
		arg.ExecutionTimeframe,
		arg.Direction,
		arg.DetectedPrice,
		arg.TheoreticalSl,
		arg.TheoreticalTp,
		arg.ProjectedRr,
		arg.Confidence,
		arg.Status,
	)
	var i Signal
	err := row.Scan(
		&i.ID,
		&i.PatternDetectionID,
		&i.Symbol,
		&i.Timeframe,
		&i.ExecutionTimeframe,
		&i.Direction,
		&i.DetectedPrice,
		&i.TheoreticalSl,
		&i.TheoreticalTp,
		&i.ProjectedRr,
		&i.Confidence,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateSignalStatus = `-- name: UpdateSignalStatus :one
UPDATE signals SET status = $2 WHERE id = $1
RETURNING id, pattern_detection_id, symbol, timeframe, execution_timeframe, direction, detected_price, theoretical_sl, theoretical_tp, projected_rr, confidence, status, created_at
`

type UpdateSignalStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateSignalStatus(ctx context.Context, arg UpdateSignalStatusParams) (Signal, error) {
	row := q.db.QueryRow(ctx, updateSignalStatus, arg.ID, arg.Status)
	var i Signal
	err := row.Scan(
		&i.ID,
		&i.PatternDetectionID,
		&i.Symbol,
		&i.Timeframe,
		&i.ExecutionTimeframe,
		&i.Direction,
		&i.DetectedPrice,
		&i.TheoreticalSl,
		&i.TheoreticalTp,
		&i.ProjectedRr,
		&i.Confidence,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
