// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetAccount(ctx context.Context, id uuid.UUID) (Account, error)
	GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error)
	ListAccountsByUser(ctx context.Context, userID uuid.UUID) ([]Account, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
}

var _ Querier = (*Queries)(nil)
