// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountCandlesD1(ctx context.Context) (int64, error)
	CountCandlesH1(ctx context.Context) (int64, error)
	CountCandlesH4(ctx context.Context) (int64, error)
	CountPatternDetections(ctx context.Context, arg CountPatternDetectionsParams) (int64, error)
	CountSignalsByStatus(ctx context.Context, status string) (int64, error)
	CreateTrade(ctx context.Context, arg CreateTradeParams) (Trade, error)
	CreateTradeExecution(ctx context.Context, arg CreateTradeExecutionParams) (TradeExecution, error)
	CreateTradeFeedback(ctx context.Context, arg CreateTradeFeedbackParams) (TradeFeedback, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteTradeFeedback(ctx context.Context, tradeID uuid.UUID) error
	GetCandleD1ByTimestamp(ctx context.Context, timestampUtc pgtype.Timestamptz) (CandlesD1, error)
	GetCandleH1ByTimestamp(ctx context.Context, timestampUtc pgtype.Timestamptz) (CandlesH1, error)
	GetCandleH4ByTimestamp(ctx context.Context, timestampUtc pgtype.Timestamptz) (CandlesH4, error)
	GetCandlesD1ByRange(ctx context.Context, arg GetCandlesD1ByRangeParams) ([]CandlesD1, error)
	GetCandlesD1BySymbolAndRange(ctx context.Context, arg GetCandlesD1BySymbolAndRangeParams) ([]CandlesD1, error)
	GetCandlesD1Last(ctx context.Context, limit int32) ([]CandlesD1, error)
	GetCandlesH1ByRange(ctx context.Context, arg GetCandlesH1ByRangeParams) ([]CandlesH1, error)
	GetCandlesH1BySymbolAndRange(ctx context.Context, arg GetCandlesH1BySymbolAndRangeParams) ([]CandlesH1, error)
	GetCandlesH1Last(ctx context.Context, limit int32) ([]CandlesH1, error)
	GetCandlesH4ByRange(ctx context.Context, arg GetCandlesH4ByRangeParams) ([]CandlesH4, error)
	GetCandlesH4BySymbolAndRange(ctx context.Context, arg GetCandlesH4BySymbolAndRangeParams) ([]CandlesH4, error)
	GetCandlesH4Last(ctx context.Context, limit int32) ([]CandlesH4, error)
	GetCandlesWeeklyByRange(ctx context.Context, arg GetCandlesWeeklyByRangeParams) ([]CandlesWeekly, error)
	GetCandlesWeeklyBySymbolAndRange(ctx context.Context, arg GetCandlesWeeklyBySymbolAndRangeParams) ([]CandlesWeekly, error)
	GetDistinctSymbolsFromWeekly(ctx context.Context) ([]string, error)
	GetIndicatorD1ByCandleID(ctx context.Context, candleID uuid.UUID) (IndicatorsD1, error)
	GetIndicatorH1ByCandleID(ctx context.Context, candleID uuid.UUID) (IndicatorsH1, error)
	GetIndicatorH4ByCandleID(ctx context.Context, candleID uuid.UUID) (IndicatorsH4, error)
	GetPatternDetectionByID(ctx context.Context, id uuid.UUID) (PatternDetection, error)
	GetPatternDetectionsByConfidence(ctx context.Context, arg GetPatternDetectionsByConfidenceParams) ([]PatternDetection, error)
	GetPatternDetectionsByTimeframe(ctx context.Context, arg GetPatternDetectionsByTimeframeParams) ([]PatternDetection, error)
	GetSignalByID(ctx context.Context, id uuid.UUID) (Signal, error)
	GetSignalsByPattern(ctx context.Context, patternDetectionID uuid.UUID) ([]Signal, error)
	GetSignalsByStatus(ctx context.Context, arg GetSignalsByStatusParams) ([]Signal, error)
	GetTradeByID(ctx context.Context, id uuid.UUID) (Trade, error)
	GetTradeExecutions(ctx context.Context, tradeID uuid.UUID) ([]TradeExecution, error)
	GetTradeFeedbackByTradeID(ctx context.Context, tradeID uuid.UUID) (TradeFeedback, error)
	GetTradesByAccountAndCandle(ctx context.Context, arg GetTradesByAccountAndCandleParams) ([]Trade, error)
	GetTradesByUserID(ctx context.Context, arg GetTradesByUserIDParams) ([]Trade, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	InsertCandleD1(ctx context.Context, arg InsertCandleD1Params) (CandlesD1, error)
	InsertCandleH1(ctx context.Context, arg InsertCandleH1Params) (CandlesH1, error)
	InsertCandleH4(ctx context.Context, arg InsertCandleH4Params) (CandlesH4, error)
	InsertIndicatorD1(ctx context.Context, arg InsertIndicatorD1Params) (IndicatorsD1, error)
	InsertIndicatorH1(ctx context.Context, arg InsertIndicatorH1Params) (IndicatorsH1, error)
	InsertIndicatorH4(ctx context.Context, arg InsertIndicatorH4Params) (IndicatorsH4, error)
	InsertPatternDetection(ctx context.Context, arg InsertPatternDetectionParams) (PatternDetection, error)
	InsertSignal(ctx context.Context, arg InsertSignalParams) (Signal, error)
	ResetPassword(ctx context.Context, arg ResetPasswordParams) error
	SetEmailVerificationToken(ctx context.Context, arg SetEmailVerificationTokenParams) error
	SetPasswordResetToken(ctx context.Context, arg SetPasswordResetTokenParams) error
	UpdateSignalStatus(ctx context.Context, arg UpdateSignalStatusParams) (Signal, error)
	UpdateTradeFeedback(ctx context.Context, arg UpdateTradeFeedbackParams) (TradeFeedback, error)
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	VerifyEmail(ctx context.Context, emailVerificationToken pgtype.Text) error
}

var _ Querier = (*Queries)(nil)
