// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trades.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createTrade = `-- name: CreateTrade :one
INSERT INTO trades (
    user_id,
    account_id,
    candle_id,
    symbol,
    timeframe,
    direction,
    planned_entry,
    stop_loss,
    take_profit,
    risk_percent
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, user_id, account_id, candle_id, symbol, timeframe, direction, planned_entry, stop_loss, take_profit, risk_percent, created_at
`

type CreateTradeParams struct {
	UserID       uuid.UUID       `json:"user_id"`
	AccountID    uuid.UUID       `json:"account_id"`
	CandleID     uuid.UUID       `json:"candle_id"`
	Symbol       string          `json:"symbol"`
	Timeframe    string          `json:"timeframe"`
	Direction    TradeDirection  `json:"direction"`
	PlannedEntry decimal.Decimal `json:"planned_entry"`
	StopLoss     decimal.Decimal `json:"stop_loss"`
	TakeProfit   decimal.Decimal `json:"take_profit"`
	RiskPercent  decimal.Decimal `json:"risk_percent"`
}

func (q *Queries) CreateTrade(ctx context.Context, arg CreateTradeParams) (Trade, error) {
	row := q.db.QueryRow(ctx, createTrade,
		arg.UserID,
		arg.AccountID,
		arg.CandleID,
		arg.Symbol,
		arg.Timeframe,
		arg.Direction,
		arg.PlannedEntry,
		arg.StopLoss,
		arg.TakeProfit,
		arg.RiskPercent,
	)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CandleID,
		&i.Symbol,
		&i.Timeframe,
		&i.Direction,
		&i.PlannedEntry,
		&i.StopLoss,
		&i.TakeProfit,
		&i.RiskPercent,
		&i.CreatedAt,
	)
	return i, err
}

const createTradeExecution = `-- name: CreateTradeExecution :one
INSERT INTO trade_executions (
    trade_id,
    execution_type,
    price,
    quantity,
    executed_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, trade_id, execution_type, price, quantity, executed_at
`

type CreateTradeExecutionParams struct {
	TradeID       uuid.UUID          `json:"trade_id"`
	ExecutionType ExecutionType      `json:"execution_type"`
	Price         decimal.Decimal    `json:"price"`
	Quantity      decimal.Decimal    `json:"quantity"`
	ExecutedAt    pgtype.Timestamptz `json:"executed_at"`
}

func (q *Queries) CreateTradeExecution(ctx context.Context, arg CreateTradeExecutionParams) (TradeExecution, error) {
	row := q.db.QueryRow(ctx, createTradeExecution,
		arg.TradeID,
		arg.ExecutionType,
		arg.Price,
		arg.Quantity,
		arg.ExecutedAt,
	)
	var i TradeExecution
	err := row.Scan(
		&i.ID,
		&i.TradeID,
		&i.ExecutionType,
		&i.Price,
		&i.Quantity,
		&i.ExecutedAt,
	)
	return i, err
}

const getTradeByID = `-- name: GetTradeByID :one
SELECT id, user_id, account_id, candle_id, symbol, timeframe, direction, planned_entry, stop_loss, take_profit, risk_percent, created_at FROM trades
WHERE id = $1
`

func (q *Queries) GetTradeByID(ctx context.Context, id uuid.UUID) (Trade, error) {
	row := q.db.QueryRow(ctx, getTradeByID, id)
	var i Trade
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CandleID,
		&i.Symbol,
		&i.Timeframe,
		&i.Direction,
		&i.PlannedEntry,
		&i.StopLoss,
		&i.TakeProfit,
		&i.RiskPercent,
		&i.CreatedAt,
	)
	return i, err
}

const getTradeExecutions = `-- name: GetTradeExecutions :many
SELECT id, trade_id, execution_type, price, quantity, executed_at FROM trade_executions
WHERE trade_id = $1
ORDER BY executed_at ASC
`

func (q *Queries) GetTradeExecutions(ctx context.Context, tradeID uuid.UUID) ([]TradeExecution, error) {
	rows, err := q.db.Query(ctx, getTradeExecutions, tradeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TradeExecution
	for rows.Next() {
		var i TradeExecution
		if err := rows.Scan(
			&i.ID,
			&i.TradeID,
			&i.ExecutionType,
			&i.Price,
			&i.Quantity,
			&i.ExecutedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTradesByAccountAndCandle = `-- name: GetTradesByAccountAndCandle :many
SELECT id, user_id, account_id, candle_id, symbol, timeframe, direction, planned_entry, stop_loss, take_profit, risk_percent, created_at FROM trades
WHERE account_id = $1
  AND candle_id = $2
ORDER BY created_at DESC
`

type GetTradesByAccountAndCandleParams struct {
	AccountID uuid.UUID `json:"account_id"`
	CandleID  uuid.UUID `json:"candle_id"`
}

func (q *Queries) GetTradesByAccountAndCandle(ctx context.Context, arg GetTradesByAccountAndCandleParams) ([]Trade, error) {
	rows, err := q.db.Query(ctx, getTradesByAccountAndCandle, arg.AccountID, arg.CandleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.CandleID,
			&i.Symbol,
			&i.Timeframe,
			&i.Direction,
			&i.PlannedEntry,
			&i.StopLoss,
			&i.TakeProfit,
			&i.RiskPercent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTradesByUserID = `-- name: GetTradesByUserID :many
SELECT id, user_id, account_id, candle_id, symbol, timeframe, direction, planned_entry, stop_loss, take_profit, risk_percent, created_at FROM trades
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetTradesByUserIDParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) GetTradesByUserID(ctx context.Context, arg GetTradesByUserIDParams) ([]Trade, error) {
	rows, err := q.db.Query(ctx, getTradesByUserID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trade
	for rows.Next() {
		var i Trade
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.CandleID,
			&i.Symbol,
			&i.Timeframe,
			&i.Direction,
			&i.PlannedEntry,
			&i.StopLoss,
			&i.TakeProfit,
			&i.RiskPercent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
