// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trade_feedback.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTradeFeedback = `-- name: CreateTradeFeedback :one
INSERT INTO trade_feedback (
    id,
    trade_id,
    followed_plan,
    emotion_before,
    emotion_during,
    emotion_after,
    biggest_mistake,
    screenshot_url
) VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
) RETURNING id, trade_id, followed_plan, emotion_before, emotion_during, emotion_after, biggest_mistake, screenshot_url, feedback_at
`

type CreateTradeFeedbackParams struct {
	TradeID        uuid.UUID   `json:"trade_id"`
	FollowedPlan   bool        `json:"followed_plan"`
	EmotionBefore  EmotionType `json:"emotion_before"`
	EmotionDuring  EmotionType `json:"emotion_during"`
	EmotionAfter   EmotionType `json:"emotion_after"`
	BiggestMistake pgtype.Text `json:"biggest_mistake"`
	ScreenshotUrl  pgtype.Text `json:"screenshot_url"`
}

func (q *Queries) CreateTradeFeedback(ctx context.Context, arg CreateTradeFeedbackParams) (TradeFeedback, error) {
	row := q.db.QueryRow(ctx, createTradeFeedback,
		arg.TradeID,
		arg.FollowedPlan,
		arg.EmotionBefore,
		arg.EmotionDuring,
		arg.EmotionAfter,
		arg.BiggestMistake,
		arg.ScreenshotUrl,
	)
	var i TradeFeedback
	err := row.Scan(
		&i.ID,
		&i.TradeID,
		&i.FollowedPlan,
		&i.EmotionBefore,
		&i.EmotionDuring,
		&i.EmotionAfter,
		&i.BiggestMistake,
		&i.ScreenshotUrl,
		&i.FeedbackAt,
	)
	return i, err
}

const deleteTradeFeedback = `-- name: DeleteTradeFeedback :exec
DELETE FROM trade_feedback WHERE trade_id = $1
`

func (q *Queries) DeleteTradeFeedback(ctx context.Context, tradeID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTradeFeedback, tradeID)
	return err
}

const getTradeFeedbackByTradeID = `-- name: GetTradeFeedbackByTradeID :one
SELECT id, trade_id, followed_plan, emotion_before, emotion_during, emotion_after, biggest_mistake, screenshot_url, feedback_at FROM trade_feedback WHERE trade_id = $1
`

func (q *Queries) GetTradeFeedbackByTradeID(ctx context.Context, tradeID uuid.UUID) (TradeFeedback, error) {
	row := q.db.QueryRow(ctx, getTradeFeedbackByTradeID, tradeID)
	var i TradeFeedback
	err := row.Scan(
		&i.ID,
		&i.TradeID,
		&i.FollowedPlan,
		&i.EmotionBefore,
		&i.EmotionDuring,
		&i.EmotionAfter,
		&i.BiggestMistake,
		&i.ScreenshotUrl,
		&i.FeedbackAt,
	)
	return i, err
}

const updateTradeFeedback = `-- name: UpdateTradeFeedback :one
UPDATE trade_feedback
SET
    followed_plan = $2,
    emotion_before = $3,
    emotion_during = $4,
    emotion_after = $5,
    biggest_mistake = $6,
    screenshot_url = $7
WHERE trade_id = $1
RETURNING id, trade_id, followed_plan, emotion_before, emotion_during, emotion_after, biggest_mistake, screenshot_url, feedback_at
`

type UpdateTradeFeedbackParams struct {
	TradeID        uuid.UUID   `json:"trade_id"`
	FollowedPlan   bool        `json:"followed_plan"`
	EmotionBefore  EmotionType `json:"emotion_before"`
	EmotionDuring  EmotionType `json:"emotion_during"`
	EmotionAfter   EmotionType `json:"emotion_after"`
	BiggestMistake pgtype.Text `json:"biggest_mistake"`
	ScreenshotUrl  pgtype.Text `json:"screenshot_url"`
}

func (q *Queries) UpdateTradeFeedback(ctx context.Context, arg UpdateTradeFeedbackParams) (TradeFeedback, error) {
	row := q.db.QueryRow(ctx, updateTradeFeedback,
		arg.TradeID,
		arg.FollowedPlan,
		arg.EmotionBefore,
		arg.EmotionDuring,
		arg.EmotionAfter,
		arg.BiggestMistake,
		arg.ScreenshotUrl,
	)
	var i TradeFeedback
	err := row.Scan(
		&i.ID,
		&i.TradeID,
		&i.FollowedPlan,
		&i.EmotionBefore,
		&i.EmotionDuring,
		&i.EmotionAfter,
		&i.BiggestMistake,
		&i.ScreenshotUrl,
		&i.FeedbackAt,
	)
	return i, err
}
